#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;


namespace RidocciModel	
{
	public partial class RdcModel : OpenAccessContext, IRdcModelUnitOfWork
	{
		private static string connectionStringName = @"Ariclinic_ridocciConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams.rlinq");
	
		public RdcModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public RdcModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public RdcModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public RdcModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public RdcModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Visita_tratamiento> Visita_tratamientos 
		{
	    	get
	    	{
	        	return this.GetAll<Visita_tratamiento>();
	    	}
		}
		
		public IQueryable<Visita_diagnostico_asignado> Visita_diagnostico_asignados 
		{
	    	get
	    	{
	        	return this.GetAll<Visita_diagnostico_asignado>();
	    	}
		}
		
		public IQueryable<Visitum> Visita 
		{
	    	get
	    	{
	        	return this.GetAll<Visitum>();
	    	}
		}
		
		public IQueryable<Usuario> Usuarios 
		{
	    	get
	    	{
	        	return this.GetAll<Usuario>();
	    	}
		}
		
		public IQueryable<Unidad> Unidads 
		{
	    	get
	    	{
	        	return this.GetAll<Unidad>();
	    	}
		}
		
		public IQueryable<Tratamiento> Tratamientos 
		{
	    	get
	    	{
	        	return this.GetAll<Tratamiento>();
	    	}
		}
		
		public IQueryable<Tipo_servicio> Tipo_servicios 
		{
	    	get
	    	{
	        	return this.GetAll<Tipo_servicio>();
	    	}
		}
		
		public IQueryable<Tipo_iva> Tipo_ivas 
		{
	    	get
	    	{
	        	return this.GetAll<Tipo_iva>();
	    	}
		}
		
		public IQueryable<Tipo_citum> Tipo_cita 
		{
	    	get
	    	{
	        	return this.GetAll<Tipo_citum>();
	    	}
		}
		
		public IQueryable<Servicio> Servicios 
		{
	    	get
	    	{
	        	return this.GetAll<Servicio>();
	    	}
		}
		
		public IQueryable<Prueba> Pruebas 
		{
	    	get
	    	{
	        	return this.GetAll<Prueba>();
	    	}
		}
		
		public IQueryable<Profesional> Profesionals 
		{
	    	get
	    	{
	        	return this.GetAll<Profesional>();
	    	}
		}
		
		public IQueryable<Procedencium> Procedencia 
		{
	    	get
	    	{
	        	return this.GetAll<Procedencium>();
	    	}
		}
		
		public IQueryable<Nota_servicio_linea_pago> Nota_servicio_linea_pagos 
		{
	    	get
	    	{
	        	return this.GetAll<Nota_servicio_linea_pago>();
	    	}
		}
		
		public IQueryable<Nota_servicio_linea_notum> Nota_servicio_linea_nota 
		{
	    	get
	    	{
	        	return this.GetAll<Nota_servicio_linea_notum>();
	    	}
		}
		
		public IQueryable<Nota_servicio> Nota_servicios 
		{
	    	get
	    	{
	        	return this.GetAll<Nota_servicio>();
	    	}
		}
		
		public IQueryable<Motivo_visitum> Motivo_visita 
		{
	    	get
	    	{
	        	return this.GetAll<Motivo_visitum>();
	    	}
		}
		
		public IQueryable<Linea_pago> Linea_pagos 
		{
	    	get
	    	{
	        	return this.GetAll<Linea_pago>();
	    	}
		}
		
		public IQueryable<Linea_notum> Linea_nota 
		{
	    	get
	    	{
	        	return this.GetAll<Linea_notum>();
	    	}
		}
		
		public IQueryable<Linea_factura> Linea_facturas 
		{
	    	get
	    	{
	        	return this.GetAll<Linea_factura>();
	    	}
		}
		
		public IQueryable<Historial_visitum> Historial_visita 
		{
	    	get
	    	{
	        	return this.GetAll<Historial_visitum>();
	    	}
		}
		
		public IQueryable<Historial_tratamiento> Historial_tratamientos 
		{
	    	get
	    	{
	        	return this.GetAll<Historial_tratamiento>();
	    	}
		}
		
		public IQueryable<Historial_diagnostico_asignado> Historial_diagnostico_asignados 
		{
	    	get
	    	{
	        	return this.GetAll<Historial_diagnostico_asignado>();
	    	}
		}
		
		public IQueryable<Historial_acto_medico_asg> Historial_acto_medico_asgs 
		{
	    	get
	    	{
	        	return this.GetAll<Historial_acto_medico_asg>();
	    	}
		}
		
		public IQueryable<Historial> Historials 
		{
	    	get
	    	{
	        	return this.GetAll<Historial>();
	    	}
		}
		
		public IQueryable<Forma_pago> Forma_pagos 
		{
	    	get
	    	{
	        	return this.GetAll<Forma_pago>();
	    	}
		}
		
		public IQueryable<Farmaco> Farmacos 
		{
	    	get
	    	{
	        	return this.GetAll<Farmaco>();
	    	}
		}
		
		public IQueryable<Factura_linea_factura> Factura_linea_facturas 
		{
	    	get
	    	{
	        	return this.GetAll<Factura_linea_factura>();
	    	}
		}
		
		public IQueryable<Factura_base_factura> Factura_base_facturas 
		{
	    	get
	    	{
	        	return this.GetAll<Factura_base_factura>();
	    	}
		}
		
		public IQueryable<Factura> Facturas 
		{
	    	get
	    	{
	        	return this.GetAll<Factura>();
	    	}
		}
		
		public IQueryable<Empresa_sanitaria_clinica> Empresa_sanitaria_clinicas 
		{
	    	get
	    	{
	        	return this.GetAll<Empresa_sanitaria_clinica>();
	    	}
		}
		
		public IQueryable<Empresa_sanitarium> Empresa_sanitaria 
		{
	    	get
	    	{
	        	return this.GetAll<Empresa_sanitarium>();
	    	}
		}
		
		public IQueryable<Diagnostico_asignado> Diagnostico_asignados 
		{
	    	get
	    	{
	        	return this.GetAll<Diagnostico_asignado>();
	    	}
		}
		
		public IQueryable<Diagnostico> Diagnosticos 
		{
	    	get
	    	{
	        	return this.GetAll<Diagnostico>();
	    	}
		}
		
		public IQueryable<Clinica_profesional> Clinica_profesionals 
		{
	    	get
	    	{
	        	return this.GetAll<Clinica_profesional>();
	    	}
		}
		
		public IQueryable<Clinica> Clinicas 
		{
	    	get
	    	{
	        	return this.GetAll<Clinica>();
	    	}
		}
		
		public IQueryable<Cita_diagnostico_asignado> Cita_diagnostico_asignados 
		{
	    	get
	    	{
	        	return this.GetAll<Cita_diagnostico_asignado>();
	    	}
		}
		
		public IQueryable<Citum> Cita 
		{
	    	get
	    	{
	        	return this.GetAll<Citum>();
	    	}
		}
		
		public IQueryable<Categoria_profesional> Categoria_profesionals 
		{
	    	get
	    	{
	        	return this.GetAll<Categoria_profesional>();
	    	}
		}
		
		public IQueryable<Base_factura> Base_facturas 
		{
	    	get
	    	{
	        	return this.GetAll<Base_factura>();
	    	}
		}
		
		public IQueryable<Aseguradora> Aseguradoras 
		{
	    	get
	    	{
	        	return this.GetAll<Aseguradora>();
	    	}
		}
		
		public IQueryable<Antecedente_personal> Antecedente_personals 
		{
	    	get
	    	{
	        	return this.GetAll<Antecedente_personal>();
	    	}
		}
		
		public IQueryable<Antecedente_ginecologico> Antecedente_ginecologicos 
		{
	    	get
	    	{
	        	return this.GetAll<Antecedente_ginecologico>();
	    	}
		}
		
		public IQueryable<Antecedente_familiar> Antecedente_familiars 
		{
	    	get
	    	{
	        	return this.GetAll<Antecedente_familiar>();
	    	}
		}
		
		public IQueryable<Analisis_prueba> Analisis_pruebas 
		{
	    	get
	    	{
	        	return this.GetAll<Analisis_prueba>();
	    	}
		}
		
		public IQueryable<Analisi> Analisis 
		{
	    	get
	    	{
	        	return this.GetAll<Analisi>();
	    	}
		}
		
		public IQueryable<Agenda> Agendas 
		{
	    	get
	    	{
	        	return this.GetAll<Agenda>();
	    	}
		}
		
		public IQueryable<Acto_medico_asg> Acto_medico_asgs 
		{
	    	get
	    	{
	        	return this.GetAll<Acto_medico_asg>();
	    	}
		}
		
		public IQueryable<Acto_medico_asc> Acto_medico_ascs 
		{
	    	get
	    	{
	        	return this.GetAll<Acto_medico_asc>();
	    	}
		}
		
		public IQueryable<Acto_medico> Acto_medicos 
		{
	    	get
	    	{
	        	return this.GetAll<Acto_medico>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mysql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}

	public interface IRdcModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Visita_tratamiento> Visita_tratamientos 
		{ 
			get;
		}
		IQueryable<Visita_diagnostico_asignado> Visita_diagnostico_asignados 
		{ 
			get;
		}
		IQueryable<Visitum> Visita 
		{ 
			get;
		}
		IQueryable<Usuario> Usuarios 
		{ 
			get;
		}
		IQueryable<Unidad> Unidads 
		{ 
			get;
		}
		IQueryable<Tratamiento> Tratamientos 
		{ 
			get;
		}
		IQueryable<Tipo_servicio> Tipo_servicios 
		{ 
			get;
		}
		IQueryable<Tipo_iva> Tipo_ivas 
		{ 
			get;
		}
		IQueryable<Tipo_citum> Tipo_cita 
		{ 
			get;
		}
		IQueryable<Servicio> Servicios 
		{ 
			get;
		}
		IQueryable<Prueba> Pruebas 
		{ 
			get;
		}
		IQueryable<Profesional> Profesionals 
		{ 
			get;
		}
		IQueryable<Procedencium> Procedencia 
		{ 
			get;
		}
		IQueryable<Nota_servicio_linea_pago> Nota_servicio_linea_pagos 
		{ 
			get;
		}
		IQueryable<Nota_servicio_linea_notum> Nota_servicio_linea_nota 
		{ 
			get;
		}
		IQueryable<Nota_servicio> Nota_servicios 
		{ 
			get;
		}
		IQueryable<Motivo_visitum> Motivo_visita 
		{ 
			get;
		}
		IQueryable<Linea_pago> Linea_pagos 
		{ 
			get;
		}
		IQueryable<Linea_notum> Linea_nota 
		{ 
			get;
		}
		IQueryable<Linea_factura> Linea_facturas 
		{ 
			get;
		}
		IQueryable<Historial_visitum> Historial_visita 
		{ 
			get;
		}
		IQueryable<Historial_tratamiento> Historial_tratamientos 
		{ 
			get;
		}
		IQueryable<Historial_diagnostico_asignado> Historial_diagnostico_asignados 
		{ 
			get;
		}
		IQueryable<Historial_acto_medico_asg> Historial_acto_medico_asgs 
		{ 
			get;
		}
		IQueryable<Historial> Historials 
		{ 
			get;
		}
		IQueryable<Forma_pago> Forma_pagos 
		{ 
			get;
		}
		IQueryable<Farmaco> Farmacos 
		{ 
			get;
		}
		IQueryable<Factura_linea_factura> Factura_linea_facturas 
		{ 
			get;
		}
		IQueryable<Factura_base_factura> Factura_base_facturas 
		{ 
			get;
		}
		IQueryable<Factura> Facturas 
		{ 
			get;
		}
		IQueryable<Empresa_sanitaria_clinica> Empresa_sanitaria_clinicas 
		{ 
			get;
		}
		IQueryable<Empresa_sanitarium> Empresa_sanitaria 
		{ 
			get;
		}
		IQueryable<Diagnostico_asignado> Diagnostico_asignados 
		{ 
			get;
		}
		IQueryable<Diagnostico> Diagnosticos 
		{ 
			get;
		}
		IQueryable<Clinica_profesional> Clinica_profesionals 
		{ 
			get;
		}
		IQueryable<Clinica> Clinicas 
		{ 
			get;
		}
		IQueryable<Cita_diagnostico_asignado> Cita_diagnostico_asignados 
		{ 
			get;
		}
		IQueryable<Citum> Cita 
		{ 
			get;
		}
		IQueryable<Categoria_profesional> Categoria_profesionals 
		{ 
			get;
		}
		IQueryable<Base_factura> Base_facturas 
		{ 
			get;
		}
		IQueryable<Aseguradora> Aseguradoras 
		{ 
			get;
		}
		IQueryable<Antecedente_personal> Antecedente_personals 
		{ 
			get;
		}
		IQueryable<Antecedente_ginecologico> Antecedente_ginecologicos 
		{ 
			get;
		}
		IQueryable<Antecedente_familiar> Antecedente_familiars 
		{ 
			get;
		}
		IQueryable<Analisis_prueba> Analisis_pruebas 
		{ 
			get;
		}
		IQueryable<Analisi> Analisis 
		{ 
			get;
		}
		IQueryable<Agenda> Agendas 
		{ 
			get;
		}
		IQueryable<Acto_medico_asg> Acto_medico_asgs 
		{ 
			get;
		}
		IQueryable<Acto_medico_asc> Acto_medico_ascs 
		{ 
			get;
		}
		IQueryable<Acto_medico> Acto_medicos 
		{ 
			get;
		}
	}
}

namespace RidocciModel	
{
	public partial class Visita_tratamiento
	{
		private int _idVisita;
		public virtual int Id_visita 
		{ 
		    get
		    {
		        return this._idVisita;
		    }
		    set
		    {
		        this._idVisita = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idTratamiento;
		public virtual int? Id_tratamiento 
		{ 
		    get
		    {
		        return this._idTratamiento;
		    }
		    set
		    {
		        this._idTratamiento = value;
		    }
		}
		
		private Tratamiento _tratamiento;
		public virtual Tratamiento Tratamiento 
		{ 
		    get
		    {
		        return this._tratamiento;
		    }
		    set
		    {
		        this._tratamiento = value;
		    }
		}
		
		private Visitum _visitum;
		public virtual Visitum Visitum 
		{ 
		    get
		    {
		        return this._visitum;
		    }
		    set
		    {
		        this._visitum = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Visita_diagnostico_asignado
	{
		private int _idVisita;
		public virtual int Id_visita 
		{ 
		    get
		    {
		        return this._idVisita;
		    }
		    set
		    {
		        this._idVisita = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idDiagnosticoAsignado;
		public virtual int? Id_diagnostico_asignado 
		{ 
		    get
		    {
		        return this._idDiagnosticoAsignado;
		    }
		    set
		    {
		        this._idDiagnosticoAsignado = value;
		    }
		}
		
		private Diagnostico_asignado _diagnosticoAsignado;
		public virtual Diagnostico_asignado Diagnostico_asignado 
		{ 
		    get
		    {
		        return this._diagnosticoAsignado;
		    }
		    set
		    {
		        this._diagnosticoAsignado = value;
		    }
		}
		
		private Visitum _visitum;
		public virtual Visitum Visitum 
		{ 
		    get
		    {
		        return this._visitum;
		    }
		    set
		    {
		        this._visitum = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Visitum
	{
		private DateTime _fechaHora;
		public virtual DateTime Fecha_hora 
		{ 
		    get
		    {
		        return this._fechaHora;
		    }
		    set
		    {
		        this._fechaHora = value;
		    }
		}
		
		private int _idVisita;
		public virtual int Id_visita 
		{ 
		    get
		    {
		        return this._idVisita;
		    }
		    set
		    {
		        this._idVisita = value;
		    }
		}
		
		private int? _idMotivo;
		public virtual int? Id_motivo 
		{ 
		    get
		    {
		        return this._idMotivo;
		    }
		    set
		    {
		        this._idMotivo = value;
		    }
		}
		
		private int? _idHistoria;
		public virtual int? Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private int? _idProfesional;
		public virtual int? Id_profesional 
		{ 
		    get
		    {
		        return this._idProfesional;
		    }
		    set
		    {
		        this._idProfesional = value;
		    }
		}
		
		private string _resumenGeneral;
		public virtual string Resumen_general 
		{ 
		    get
		    {
		        return this._resumenGeneral;
		    }
		    set
		    {
		        this._resumenGeneral = value;
		    }
		}
		
		private int? _idTipoCita;
		public virtual int? Id_tipo_cita 
		{ 
		    get
		    {
		        return this._idTipoCita;
		    }
		    set
		    {
		        this._idTipoCita = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Visita_tratamiento> _visitaTratamientos = new List<Visita_tratamiento>();
		public virtual IList<Visita_tratamiento> Visita_tratamientos 
		{ 
		    get
		    {
		        return this._visitaTratamientos;
		    }
		}
		
		private IList<Visita_diagnostico_asignado> _visitaDiagnosticoAsignados = new List<Visita_diagnostico_asignado>();
		public virtual IList<Visita_diagnostico_asignado> Visita_diagnostico_asignados 
		{ 
		    get
		    {
		        return this._visitaDiagnosticoAsignados;
		    }
		}
		
		private IList<Historial_visitum> _historialVisita = new List<Historial_visitum>();
		public virtual IList<Historial_visitum> Historial_visita 
		{ 
		    get
		    {
		        return this._historialVisita;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Usuario
	{
		private int _idUsuario;
		public virtual int Id_usuario 
		{ 
		    get
		    {
		        return this._idUsuario;
		    }
		    set
		    {
		        this._idUsuario = value;
		    }
		}
		
		private string _login;
		public virtual string Login 
		{ 
		    get
		    {
		        return this._login;
		    }
		    set
		    {
		        this._login = value;
		    }
		}
		
		private int _nivel;
		public virtual int Nivel 
		{ 
		    get
		    {
		        return this._nivel;
		    }
		    set
		    {
		        this._nivel = value;
		    }
		}
		
		private string _passwd;
		public virtual string Passwd 
		{ 
		    get
		    {
		        return this._passwd;
		    }
		    set
		    {
		        this._passwd = value;
		    }
		}
		
		private int? _idProfesional;
		public virtual int? Id_profesional 
		{ 
		    get
		    {
		        return this._idProfesional;
		    }
		    set
		    {
		        this._idProfesional = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Unidad
	{
		private int _idUnidad;
		public virtual int Id_unidad 
		{ 
		    get
		    {
		        return this._idUnidad;
		    }
		    set
		    {
		        this._idUnidad = value;
		    }
		}
		
		private string _nomUnidad;
		public virtual string Nom_unidad 
		{ 
		    get
		    {
		        return this._nomUnidad;
		    }
		    set
		    {
		        this._nomUnidad = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Prueba> _pruebas = new List<Prueba>();
		public virtual IList<Prueba> Pruebas 
		{ 
		    get
		    {
		        return this._pruebas;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Tratamiento
	{
		private int? _idFarmaco;
		public virtual int? Id_farmaco 
		{ 
		    get
		    {
		        return this._idFarmaco;
		    }
		    set
		    {
		        this._idFarmaco = value;
		    }
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private int _idTratamiento;
		public virtual int Id_tratamiento 
		{ 
		    get
		    {
		        return this._idTratamiento;
		    }
		    set
		    {
		        this._idTratamiento = value;
		    }
		}
		
		private int? _idHistoria;
		public virtual int? Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private string _posologia;
		public virtual string Posologia 
		{ 
		    get
		    {
		        return this._posologia;
		    }
		    set
		    {
		        this._posologia = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private int? _idProfesional;
		public virtual int? Id_profesional 
		{ 
		    get
		    {
		        return this._idProfesional;
		    }
		    set
		    {
		        this._idProfesional = value;
		    }
		}
		
		private IList<Visita_tratamiento> _visitaTratamientos = new List<Visita_tratamiento>();
		public virtual IList<Visita_tratamiento> Visita_tratamientos 
		{ 
		    get
		    {
		        return this._visitaTratamientos;
		    }
		}
		
		private IList<Historial_tratamiento> _historialTratamientos = new List<Historial_tratamiento>();
		public virtual IList<Historial_tratamiento> Historial_tratamientos 
		{ 
		    get
		    {
		        return this._historialTratamientos;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Tipo_servicio
	{
		private int _idTipoServicio;
		public virtual int Id_tipo_servicio 
		{ 
		    get
		    {
		        return this._idTipoServicio;
		    }
		    set
		    {
		        this._idTipoServicio = value;
		    }
		}
		
		private string _nomTipoServicio;
		public virtual string Nom_tipo_servicio 
		{ 
		    get
		    {
		        return this._nomTipoServicio;
		    }
		    set
		    {
		        this._nomTipoServicio = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Tipo_iva
	{
		private int _idTipoIva;
		public virtual int Id_tipo_iva 
		{ 
		    get
		    {
		        return this._idTipoIva;
		    }
		    set
		    {
		        this._idTipoIva = value;
		    }
		}
		
		private string _nomTipoIva;
		public virtual string Nom_tipo_iva 
		{ 
		    get
		    {
		        return this._nomTipoIva;
		    }
		    set
		    {
		        this._nomTipoIva = value;
		    }
		}
		
		private float _porcentaje;
		public virtual float Porcentaje 
		{ 
		    get
		    {
		        return this._porcentaje;
		    }
		    set
		    {
		        this._porcentaje = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Tipo_citum
	{
		private int _duracion;
		public virtual int Duracion 
		{ 
		    get
		    {
		        return this._duracion;
		    }
		    set
		    {
		        this._duracion = value;
		    }
		}
		
		private int _idTipoCita;
		public virtual int Id_tipo_cita 
		{ 
		    get
		    {
		        return this._idTipoCita;
		    }
		    set
		    {
		        this._idTipoCita = value;
		    }
		}
		
		private string _nomTipoCita;
		public virtual string Nom_tipo_cita 
		{ 
		    get
		    {
		        return this._nomTipoCita;
		    }
		    set
		    {
		        this._nomTipoCita = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Servicio
	{
		private int _idServicio;
		public virtual int Id_servicio 
		{ 
		    get
		    {
		        return this._idServicio;
		    }
		    set
		    {
		        this._idServicio = value;
		    }
		}
		
		private string _nomServicio;
		public virtual string Nom_servicio 
		{ 
		    get
		    {
		        return this._nomServicio;
		    }
		    set
		    {
		        this._nomServicio = value;
		    }
		}
		
		private decimal _precioBase;
		public virtual decimal Precio_base 
		{ 
		    get
		    {
		        return this._precioBase;
		    }
		    set
		    {
		        this._precioBase = value;
		    }
		}
		
		private int? _idTipoServicio;
		public virtual int? Id_tipo_servicio 
		{ 
		    get
		    {
		        return this._idTipoServicio;
		    }
		    set
		    {
		        this._idTipoServicio = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Prueba
	{
		private int _idPrueba;
		public virtual int Id_prueba 
		{ 
		    get
		    {
		        return this._idPrueba;
		    }
		    set
		    {
		        this._idPrueba = value;
		    }
		}
		
		private string _nomPrueba;
		public virtual string Nom_prueba 
		{ 
		    get
		    {
		        return this._nomPrueba;
		    }
		    set
		    {
		        this._nomPrueba = value;
		    }
		}
		
		private int _idUnidad;
		public virtual int Id_unidad 
		{ 
		    get
		    {
		        return this._idUnidad;
		    }
		    set
		    {
		        this._idUnidad = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private Unidad _unidad;
		public virtual Unidad Unidad 
		{ 
		    get
		    {
		        return this._unidad;
		    }
		    set
		    {
		        this._unidad = value;
		    }
		}
		
		private IList<Analisis_prueba> _analisisPruebas = new List<Analisis_prueba>();
		public virtual IList<Analisis_prueba> Analisis_pruebas 
		{ 
		    get
		    {
		        return this._analisisPruebas;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Profesional
	{
		private int? _idCategoria;
		public virtual int? Id_categoria 
		{ 
		    get
		    {
		        return this._idCategoria;
		    }
		    set
		    {
		        this._idCategoria = value;
		    }
		}
		
		private int? _idClinica;
		public virtual int? Id_clinica 
		{ 
		    get
		    {
		        return this._idClinica;
		    }
		    set
		    {
		        this._idClinica = value;
		    }
		}
		
		private int _idProfesional;
		public virtual int Id_profesional 
		{ 
		    get
		    {
		        return this._idProfesional;
		    }
		    set
		    {
		        this._idProfesional = value;
		    }
		}
		
		private string _nomProfesional;
		public virtual string Nom_profesional 
		{ 
		    get
		    {
		        return this._nomProfesional;
		    }
		    set
		    {
		        this._nomProfesional = value;
		    }
		}
		
		private string _numColegiado;
		public virtual string Num_colegiado 
		{ 
		    get
		    {
		        return this._numColegiado;
		    }
		    set
		    {
		        this._numColegiado = value;
		    }
		}
		
		private int? _idUsuario;
		public virtual int? Id_usuario 
		{ 
		    get
		    {
		        return this._idUsuario;
		    }
		    set
		    {
		        this._idUsuario = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Clinica_profesional> _clinicaProfesionals = new List<Clinica_profesional>();
		public virtual IList<Clinica_profesional> Clinica_profesionals 
		{ 
		    get
		    {
		        return this._clinicaProfesionals;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Procedencium
	{
		private int _idProcedencia;
		public virtual int Id_procedencia 
		{ 
		    get
		    {
		        return this._idProcedencia;
		    }
		    set
		    {
		        this._idProcedencia = value;
		    }
		}
		
		private string _nomProcedencia;
		public virtual string Nom_procedencia 
		{ 
		    get
		    {
		        return this._nomProcedencia;
		    }
		    set
		    {
		        this._nomProcedencia = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Nota_servicio_linea_pago
	{
		private int _idNotaServicio;
		public virtual int Id_nota_servicio 
		{ 
		    get
		    {
		        return this._idNotaServicio;
		    }
		    set
		    {
		        this._idNotaServicio = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idLineaPago;
		public virtual int? Id_linea_pago 
		{ 
		    get
		    {
		        return this._idLineaPago;
		    }
		    set
		    {
		        this._idLineaPago = value;
		    }
		}
		
		private Linea_pago _lineaPago;
		public virtual Linea_pago Linea_pago 
		{ 
		    get
		    {
		        return this._lineaPago;
		    }
		    set
		    {
		        this._lineaPago = value;
		    }
		}
		
		private Nota_servicio _notaServicio;
		public virtual Nota_servicio Nota_servicio 
		{ 
		    get
		    {
		        return this._notaServicio;
		    }
		    set
		    {
		        this._notaServicio = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Nota_servicio_linea_notum
	{
		private int _idNotaServicio;
		public virtual int Id_nota_servicio 
		{ 
		    get
		    {
		        return this._idNotaServicio;
		    }
		    set
		    {
		        this._idNotaServicio = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idLineaNota;
		public virtual int? Id_linea_nota 
		{ 
		    get
		    {
		        return this._idLineaNota;
		    }
		    set
		    {
		        this._idLineaNota = value;
		    }
		}
		
		private Linea_notum _lineaNotum;
		public virtual Linea_notum Linea_notum 
		{ 
		    get
		    {
		        return this._lineaNotum;
		    }
		    set
		    {
		        this._lineaNotum = value;
		    }
		}
		
		private Nota_servicio _notaServicio;
		public virtual Nota_servicio Nota_servicio 
		{ 
		    get
		    {
		        return this._notaServicio;
		    }
		    set
		    {
		        this._notaServicio = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Nota_servicio
	{
		private DateTime _fecha;
		public virtual DateTime Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private int _idNotaServicio;
		public virtual int Id_nota_servicio 
		{ 
		    get
		    {
		        return this._idNotaServicio;
		    }
		    set
		    {
		        this._idNotaServicio = value;
		    }
		}
		
		private int _numNota;
		public virtual int Num_nota 
		{ 
		    get
		    {
		        return this._numNota;
		    }
		    set
		    {
		        this._numNota = value;
		    }
		}
		
		private int? _idHistoria;
		public virtual int? Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private decimal _pagado;
		public virtual decimal Pagado 
		{ 
		    get
		    {
		        return this._pagado;
		    }
		    set
		    {
		        this._pagado = value;
		    }
		}
		
		private int? _idProfesional;
		public virtual int? Id_profesional 
		{ 
		    get
		    {
		        return this._idProfesional;
		    }
		    set
		    {
		        this._idProfesional = value;
		    }
		}
		
		private decimal _ttal;
		public virtual decimal Ttal 
		{ 
		    get
		    {
		        return this._ttal;
		    }
		    set
		    {
		        this._ttal = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Nota_servicio_linea_pago> _notaServicioLineaPagos = new List<Nota_servicio_linea_pago>();
		public virtual IList<Nota_servicio_linea_pago> Nota_servicio_linea_pagos 
		{ 
		    get
		    {
		        return this._notaServicioLineaPagos;
		    }
		}
		
		private IList<Nota_servicio_linea_notum> _notaServicioLineaNota = new List<Nota_servicio_linea_notum>();
		public virtual IList<Nota_servicio_linea_notum> Nota_servicio_linea_nota 
		{ 
		    get
		    {
		        return this._notaServicioLineaNota;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Motivo_visitum
	{
		private int _idMotivo;
		public virtual int Id_motivo 
		{ 
		    get
		    {
		        return this._idMotivo;
		    }
		    set
		    {
		        this._idMotivo = value;
		    }
		}
		
		private string _nomMotivo;
		public virtual string Nom_motivo 
		{ 
		    get
		    {
		        return this._nomMotivo;
		    }
		    set
		    {
		        this._nomMotivo = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Linea_pago
	{
		private DateTime _fecha;
		public virtual DateTime Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private int? _idFormaPago;
		public virtual int? Id_forma_pago 
		{ 
		    get
		    {
		        return this._idFormaPago;
		    }
		    set
		    {
		        this._idFormaPago = value;
		    }
		}
		
		private int _idLineaPago;
		public virtual int Id_linea_pago 
		{ 
		    get
		    {
		        return this._idLineaPago;
		    }
		    set
		    {
		        this._idLineaPago = value;
		    }
		}
		
		private decimal _importe;
		public virtual decimal Importe 
		{ 
		    get
		    {
		        return this._importe;
		    }
		    set
		    {
		        this._importe = value;
		    }
		}
		
		private int? _idNotaServicio;
		public virtual int? Id_nota_servicio 
		{ 
		    get
		    {
		        return this._idNotaServicio;
		    }
		    set
		    {
		        this._idNotaServicio = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Nota_servicio_linea_pago> _notaServicioLineaPagos = new List<Nota_servicio_linea_pago>();
		public virtual IList<Nota_servicio_linea_pago> Nota_servicio_linea_pagos 
		{ 
		    get
		    {
		        return this._notaServicioLineaPagos;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Linea_notum
	{
		private string _concepto;
		public virtual string Concepto 
		{ 
		    get
		    {
		        return this._concepto;
		    }
		    set
		    {
		        this._concepto = value;
		    }
		}
		
		private int _idLineaNota;
		public virtual int Id_linea_nota 
		{ 
		    get
		    {
		        return this._idLineaNota;
		    }
		    set
		    {
		        this._idLineaNota = value;
		    }
		}
		
		private decimal _importe;
		public virtual decimal Importe 
		{ 
		    get
		    {
		        return this._importe;
		    }
		    set
		    {
		        this._importe = value;
		    }
		}
		
		private int? _idNotaServicio;
		public virtual int? Id_nota_servicio 
		{ 
		    get
		    {
		        return this._idNotaServicio;
		    }
		    set
		    {
		        this._idNotaServicio = value;
		    }
		}
		
		private int? _idServicio;
		public virtual int? Id_servicio 
		{ 
		    get
		    {
		        return this._idServicio;
		    }
		    set
		    {
		        this._idServicio = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Nota_servicio_linea_notum> _notaServicioLineaNota = new List<Nota_servicio_linea_notum>();
		public virtual IList<Nota_servicio_linea_notum> Nota_servicio_linea_nota 
		{ 
		    get
		    {
		        return this._notaServicioLineaNota;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Linea_factura
	{
		private decimal _bimporte;
		public virtual decimal Bimporte 
		{ 
		    get
		    {
		        return this._bimporte;
		    }
		    set
		    {
		        this._bimporte = value;
		    }
		}
		
		private decimal _cimporte;
		public virtual decimal Cimporte 
		{ 
		    get
		    {
		        return this._cimporte;
		    }
		    set
		    {
		        this._cimporte = value;
		    }
		}
		
		private string _concepto;
		public virtual string Concepto 
		{ 
		    get
		    {
		        return this._concepto;
		    }
		    set
		    {
		        this._concepto = value;
		    }
		}
		
		private int? _idFactura;
		public virtual int? Id_factura 
		{ 
		    get
		    {
		        return this._idFactura;
		    }
		    set
		    {
		        this._idFactura = value;
		    }
		}
		
		private int _idLineaFactura;
		public virtual int Id_linea_factura 
		{ 
		    get
		    {
		        return this._idLineaFactura;
		    }
		    set
		    {
		        this._idLineaFactura = value;
		    }
		}
		
		private decimal _importe;
		public virtual decimal Importe 
		{ 
		    get
		    {
		        return this._importe;
		    }
		    set
		    {
		        this._importe = value;
		    }
		}
		
		private float _porcentaje;
		public virtual float Porcentaje 
		{ 
		    get
		    {
		        return this._porcentaje;
		    }
		    set
		    {
		        this._porcentaje = value;
		    }
		}
		
		private int? _idTipoIva;
		public virtual int? Id_tipo_iva 
		{ 
		    get
		    {
		        return this._idTipoIva;
		    }
		    set
		    {
		        this._idTipoIva = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Factura_linea_factura> _facturaLineaFacturas = new List<Factura_linea_factura>();
		public virtual IList<Factura_linea_factura> Factura_linea_facturas 
		{ 
		    get
		    {
		        return this._facturaLineaFacturas;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Historial_visitum
	{
		private int _idHistoria;
		public virtual int Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idVisita;
		public virtual int? Id_visita 
		{ 
		    get
		    {
		        return this._idVisita;
		    }
		    set
		    {
		        this._idVisita = value;
		    }
		}
		
		private Historial _historial;
		public virtual Historial Historial 
		{ 
		    get
		    {
		        return this._historial;
		    }
		    set
		    {
		        this._historial = value;
		    }
		}
		
		private Visitum _visitum;
		public virtual Visitum Visitum 
		{ 
		    get
		    {
		        return this._visitum;
		    }
		    set
		    {
		        this._visitum = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Historial_tratamiento
	{
		private int _idHistoria;
		public virtual int Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idTratamiento;
		public virtual int? Id_tratamiento 
		{ 
		    get
		    {
		        return this._idTratamiento;
		    }
		    set
		    {
		        this._idTratamiento = value;
		    }
		}
		
		private Historial _historial;
		public virtual Historial Historial 
		{ 
		    get
		    {
		        return this._historial;
		    }
		    set
		    {
		        this._historial = value;
		    }
		}
		
		private Tratamiento _tratamiento;
		public virtual Tratamiento Tratamiento 
		{ 
		    get
		    {
		        return this._tratamiento;
		    }
		    set
		    {
		        this._tratamiento = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Historial_diagnostico_asignado
	{
		private int _idHistoria;
		public virtual int Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idDiagnosticoAsignado;
		public virtual int? Id_diagnostico_asignado 
		{ 
		    get
		    {
		        return this._idDiagnosticoAsignado;
		    }
		    set
		    {
		        this._idDiagnosticoAsignado = value;
		    }
		}
		
		private Diagnostico_asignado _diagnosticoAsignado;
		public virtual Diagnostico_asignado Diagnostico_asignado 
		{ 
		    get
		    {
		        return this._diagnosticoAsignado;
		    }
		    set
		    {
		        this._diagnosticoAsignado = value;
		    }
		}
		
		private Historial _historial;
		public virtual Historial Historial 
		{ 
		    get
		    {
		        return this._historial;
		    }
		    set
		    {
		        this._historial = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Historial_acto_medico_asg
	{
		private int _idHistoria;
		public virtual int Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idActoMedicoAsg;
		public virtual int? Id_acto_medico_asg 
		{ 
		    get
		    {
		        return this._idActoMedicoAsg;
		    }
		    set
		    {
		        this._idActoMedicoAsg = value;
		    }
		}
		
		private Acto_medico_asg _actoMedicoAsg;
		public virtual Acto_medico_asg Acto_medico_asg 
		{ 
		    get
		    {
		        return this._actoMedicoAsg;
		    }
		    set
		    {
		        this._actoMedicoAsg = value;
		    }
		}
		
		private Historial _historial;
		public virtual Historial Historial 
		{ 
		    get
		    {
		        return this._historial;
		    }
		    set
		    {
		        this._historial = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Historial
	{
		private string _apellidos;
		public virtual string Apellidos 
		{ 
		    get
		    {
		        return this._apellidos;
		    }
		    set
		    {
		        this._apellidos = value;
		    }
		}
		
		private string _codPostal;
		public virtual string Cod_postal 
		{ 
		    get
		    {
		        return this._codPostal;
		    }
		    set
		    {
		        this._codPostal = value;
		    }
		}
		
		private string _direccion;
		public virtual string Direccion 
		{ 
		    get
		    {
		        return this._direccion;
		    }
		    set
		    {
		        this._direccion = value;
		    }
		}
		
		private string _email;
		public virtual string Email 
		{ 
		    get
		    {
		        return this._email;
		    }
		    set
		    {
		        this._email = value;
		    }
		}
		
		private DateTime _fechaApertura;
		public virtual DateTime Fecha_apertura 
		{ 
		    get
		    {
		        return this._fechaApertura;
		    }
		    set
		    {
		        this._fechaApertura = value;
		    }
		}
		
		private DateTime _fechaNacimiento;
		public virtual DateTime Fecha_nacimiento 
		{ 
		    get
		    {
		        return this._fechaNacimiento;
		    }
		    set
		    {
		        this._fechaNacimiento = value;
		    }
		}
		
		private int _idHistoria;
		public virtual int Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private string _movil;
		public virtual string Movil 
		{ 
		    get
		    {
		        return this._movil;
		    }
		    set
		    {
		        this._movil = value;
		    }
		}
		
		private string _nif;
		public virtual string Nif 
		{ 
		    get
		    {
		        return this._nif;
		    }
		    set
		    {
		        this._nif = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private string _numHistoria;
		public virtual string Num_historia 
		{ 
		    get
		    {
		        return this._numHistoria;
		    }
		    set
		    {
		        this._numHistoria = value;
		    }
		}
		
		private string _pais;
		public virtual string Pais 
		{ 
		    get
		    {
		        return this._pais;
		    }
		    set
		    {
		        this._pais = value;
		    }
		}
		
		private string _poblacion;
		public virtual string Poblacion 
		{ 
		    get
		    {
		        return this._poblacion;
		    }
		    set
		    {
		        this._poblacion = value;
		    }
		}
		
		private int? _idProcedencia;
		public virtual int? Id_procedencia 
		{ 
		    get
		    {
		        return this._idProcedencia;
		    }
		    set
		    {
		        this._idProcedencia = value;
		    }
		}
		
		private string _provincia;
		public virtual string Provincia 
		{ 
		    get
		    {
		        return this._provincia;
		    }
		    set
		    {
		        this._provincia = value;
		    }
		}
		
		private string _sexo;
		public virtual string Sexo 
		{ 
		    get
		    {
		        return this._sexo;
		    }
		    set
		    {
		        this._sexo = value;
		    }
		}
		
		private string _telefono1;
		public virtual string Telefono1 
		{ 
		    get
		    {
		        return this._telefono1;
		    }
		    set
		    {
		        this._telefono1 = value;
		    }
		}
		
		private string _telefono2;
		public virtual string Telefono2 
		{ 
		    get
		    {
		        return this._telefono2;
		    }
		    set
		    {
		        this._telefono2 = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private int? _idAseguradora;
		public virtual int? Id_aseguradora 
		{ 
		    get
		    {
		        return this._idAseguradora;
		    }
		    set
		    {
		        this._idAseguradora = value;
		    }
		}
		
		private DateTime _fechaAltaPoliza;
		public virtual DateTime Fecha_alta_poliza 
		{ 
		    get
		    {
		        return this._fechaAltaPoliza;
		    }
		    set
		    {
		        this._fechaAltaPoliza = value;
		    }
		}
		
		private DateTime _fechaCaducidadPoliza;
		public virtual DateTime Fecha_caducidad_poliza 
		{ 
		    get
		    {
		        return this._fechaCaducidadPoliza;
		    }
		    set
		    {
		        this._fechaCaducidadPoliza = value;
		    }
		}
		
		private string _poliza;
		public virtual string Poliza 
		{ 
		    get
		    {
		        return this._poliza;
		    }
		    set
		    {
		        this._poliza = value;
		    }
		}
		
		private int? _idAntecedenteFamiliar;
		public virtual int? Id_antecedente_familiar 
		{ 
		    get
		    {
		        return this._idAntecedenteFamiliar;
		    }
		    set
		    {
		        this._idAntecedenteFamiliar = value;
		    }
		}
		
		private int? _idAntecedenteGinecologico;
		public virtual int? Id_antecedente_ginecologico 
		{ 
		    get
		    {
		        return this._idAntecedenteGinecologico;
		    }
		    set
		    {
		        this._idAntecedenteGinecologico = value;
		    }
		}
		
		private int? _idAntecedentePersonal;
		public virtual int? Id_antecedente_personal 
		{ 
		    get
		    {
		        return this._idAntecedentePersonal;
		    }
		    set
		    {
		        this._idAntecedentePersonal = value;
		    }
		}
		
		private string _historiaAnterior;
		public virtual string Historia_anterior 
		{ 
		    get
		    {
		        return this._historiaAnterior;
		    }
		    set
		    {
		        this._historiaAnterior = value;
		    }
		}
		
		private string _observaciones;
		public virtual string Observaciones 
		{ 
		    get
		    {
		        return this._observaciones;
		    }
		    set
		    {
		        this._observaciones = value;
		    }
		}
		
		private DateTime _ultimaActualizacion;
		public virtual DateTime Ultima_actualizacion 
		{ 
		    get
		    {
		        return this._ultimaActualizacion;
		    }
		    set
		    {
		        this._ultimaActualizacion = value;
		    }
		}
		
		private IList<Historial_visitum> _historialVisita = new List<Historial_visitum>();
		public virtual IList<Historial_visitum> Historial_visita 
		{ 
		    get
		    {
		        return this._historialVisita;
		    }
		}
		
		private IList<Historial_tratamiento> _historialTratamientos = new List<Historial_tratamiento>();
		public virtual IList<Historial_tratamiento> Historial_tratamientos 
		{ 
		    get
		    {
		        return this._historialTratamientos;
		    }
		}
		
		private IList<Historial_diagnostico_asignado> _historialDiagnosticoAsignados = new List<Historial_diagnostico_asignado>();
		public virtual IList<Historial_diagnostico_asignado> Historial_diagnostico_asignados 
		{ 
		    get
		    {
		        return this._historialDiagnosticoAsignados;
		    }
		}
		
		private IList<Historial_acto_medico_asg> _historialActoMedicoAsgs = new List<Historial_acto_medico_asg>();
		public virtual IList<Historial_acto_medico_asg> Historial_acto_medico_asgs 
		{ 
		    get
		    {
		        return this._historialActoMedicoAsgs;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Forma_pago
	{
		private int _idFormaPago;
		public virtual int Id_forma_pago 
		{ 
		    get
		    {
		        return this._idFormaPago;
		    }
		    set
		    {
		        this._idFormaPago = value;
		    }
		}
		
		private string _nomFormaPago;
		public virtual string Nom_forma_pago 
		{ 
		    get
		    {
		        return this._nomFormaPago;
		    }
		    set
		    {
		        this._nomFormaPago = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Farmaco
	{
		private int _idFarmaco;
		public virtual int Id_farmaco 
		{ 
		    get
		    {
		        return this._idFarmaco;
		    }
		    set
		    {
		        this._idFarmaco = value;
		    }
		}
		
		private string _nomFarmaco;
		public virtual string Nom_farmaco 
		{ 
		    get
		    {
		        return this._nomFarmaco;
		    }
		    set
		    {
		        this._nomFarmaco = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Factura_linea_factura
	{
		private int _idFactura;
		public virtual int Id_factura 
		{ 
		    get
		    {
		        return this._idFactura;
		    }
		    set
		    {
		        this._idFactura = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idLineaFactura;
		public virtual int? Id_linea_factura 
		{ 
		    get
		    {
		        return this._idLineaFactura;
		    }
		    set
		    {
		        this._idLineaFactura = value;
		    }
		}
		
		private Factura _factura;
		public virtual Factura Factura 
		{ 
		    get
		    {
		        return this._factura;
		    }
		    set
		    {
		        this._factura = value;
		    }
		}
		
		private Linea_factura _lineaFactura;
		public virtual Linea_factura Linea_factura 
		{ 
		    get
		    {
		        return this._lineaFactura;
		    }
		    set
		    {
		        this._lineaFactura = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Factura_base_factura
	{
		private int _idFactura;
		public virtual int Id_factura 
		{ 
		    get
		    {
		        return this._idFactura;
		    }
		    set
		    {
		        this._idFactura = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idBaseFactura;
		public virtual int? Id_base_factura 
		{ 
		    get
		    {
		        return this._idBaseFactura;
		    }
		    set
		    {
		        this._idBaseFactura = value;
		    }
		}
		
		private Base_factura _baseFactura;
		public virtual Base_factura Base_factura 
		{ 
		    get
		    {
		        return this._baseFactura;
		    }
		    set
		    {
		        this._baseFactura = value;
		    }
		}
		
		private Factura _factura;
		public virtual Factura Factura 
		{ 
		    get
		    {
		        return this._factura;
		    }
		    set
		    {
		        this._factura = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Factura
	{
		private int _ano;
		public virtual int Ano 
		{ 
		    get
		    {
		        return this._ano;
		    }
		    set
		    {
		        this._ano = value;
		    }
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private int _idFactura;
		public virtual int Id_factura 
		{ 
		    get
		    {
		        return this._idFactura;
		    }
		    set
		    {
		        this._idFactura = value;
		    }
		}
		
		private string _numFactura;
		public virtual string Num_factura 
		{ 
		    get
		    {
		        return this._numFactura;
		    }
		    set
		    {
		        this._numFactura = value;
		    }
		}
		
		private int _numero;
		public virtual int Numero 
		{ 
		    get
		    {
		        return this._numero;
		    }
		    set
		    {
		        this._numero = value;
		    }
		}
		
		private int? _idHistoria;
		public virtual int? Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private decimal _ttal;
		public virtual decimal Ttal 
		{ 
		    get
		    {
		        return this._ttal;
		    }
		    set
		    {
		        this._ttal = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Factura_linea_factura> _facturaLineaFacturas = new List<Factura_linea_factura>();
		public virtual IList<Factura_linea_factura> Factura_linea_facturas 
		{ 
		    get
		    {
		        return this._facturaLineaFacturas;
		    }
		}
		
		private IList<Factura_base_factura> _facturaBaseFacturas = new List<Factura_base_factura>();
		public virtual IList<Factura_base_factura> Factura_base_facturas 
		{ 
		    get
		    {
		        return this._facturaBaseFacturas;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Empresa_sanitaria_clinica
	{
		private int _idEmpresa;
		public virtual int Id_empresa 
		{ 
		    get
		    {
		        return this._idEmpresa;
		    }
		    set
		    {
		        this._idEmpresa = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idClinica;
		public virtual int? Id_clinica 
		{ 
		    get
		    {
		        return this._idClinica;
		    }
		    set
		    {
		        this._idClinica = value;
		    }
		}
		
		private Clinica _clinica;
		public virtual Clinica Clinica 
		{ 
		    get
		    {
		        return this._clinica;
		    }
		    set
		    {
		        this._clinica = value;
		    }
		}
		
		private Empresa_sanitarium _empresaSanitarium;
		public virtual Empresa_sanitarium Empresa_sanitarium 
		{ 
		    get
		    {
		        return this._empresaSanitarium;
		    }
		    set
		    {
		        this._empresaSanitarium = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Empresa_sanitarium
	{
		private int _idEmpresa;
		public virtual int Id_empresa 
		{ 
		    get
		    {
		        return this._idEmpresa;
		    }
		    set
		    {
		        this._idEmpresa = value;
		    }
		}
		
		private string _nomEmpresa;
		public virtual string Nom_empresa 
		{ 
		    get
		    {
		        return this._nomEmpresa;
		    }
		    set
		    {
		        this._nomEmpresa = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Empresa_sanitaria_clinica> _empresaSanitariaClinicas = new List<Empresa_sanitaria_clinica>();
		public virtual IList<Empresa_sanitaria_clinica> Empresa_sanitaria_clinicas 
		{ 
		    get
		    {
		        return this._empresaSanitariaClinicas;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Diagnostico_asignado
	{
		private int? _idDiagnostico;
		public virtual int? Id_diagnostico 
		{ 
		    get
		    {
		        return this._idDiagnostico;
		    }
		    set
		    {
		        this._idDiagnostico = value;
		    }
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private int _idDiagnosticoAsignado;
		public virtual int Id_diagnostico_asignado 
		{ 
		    get
		    {
		        return this._idDiagnosticoAsignado;
		    }
		    set
		    {
		        this._idDiagnosticoAsignado = value;
		    }
		}
		
		private string _observaciones;
		public virtual string Observaciones 
		{ 
		    get
		    {
		        return this._observaciones;
		    }
		    set
		    {
		        this._observaciones = value;
		    }
		}
		
		private int? _idHistoria;
		public virtual int? Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Visita_diagnostico_asignado> _visitaDiagnosticoAsignados = new List<Visita_diagnostico_asignado>();
		public virtual IList<Visita_diagnostico_asignado> Visita_diagnostico_asignados 
		{ 
		    get
		    {
		        return this._visitaDiagnosticoAsignados;
		    }
		}
		
		private IList<Historial_diagnostico_asignado> _historialDiagnosticoAsignados = new List<Historial_diagnostico_asignado>();
		public virtual IList<Historial_diagnostico_asignado> Historial_diagnostico_asignados 
		{ 
		    get
		    {
		        return this._historialDiagnosticoAsignados;
		    }
		}
		
		private IList<Cita_diagnostico_asignado> _citaDiagnosticoAsignados = new List<Cita_diagnostico_asignado>();
		public virtual IList<Cita_diagnostico_asignado> Cita_diagnostico_asignados 
		{ 
		    get
		    {
		        return this._citaDiagnosticoAsignados;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Diagnostico
	{
		private string _cie;
		public virtual string Cie 
		{ 
		    get
		    {
		        return this._cie;
		    }
		    set
		    {
		        this._cie = value;
		    }
		}
		
		private int _idDiagnostico;
		public virtual int Id_diagnostico 
		{ 
		    get
		    {
		        return this._idDiagnostico;
		    }
		    set
		    {
		        this._idDiagnostico = value;
		    }
		}
		
		private string _nomDiagnostico;
		public virtual string Nom_diagnostico 
		{ 
		    get
		    {
		        return this._nomDiagnostico;
		    }
		    set
		    {
		        this._nomDiagnostico = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Clinica_profesional
	{
		private int _idClinica;
		public virtual int Id_clinica 
		{ 
		    get
		    {
		        return this._idClinica;
		    }
		    set
		    {
		        this._idClinica = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idProfesional;
		public virtual int? Id_profesional 
		{ 
		    get
		    {
		        return this._idProfesional;
		    }
		    set
		    {
		        this._idProfesional = value;
		    }
		}
		
		private Clinica _clinica;
		public virtual Clinica Clinica 
		{ 
		    get
		    {
		        return this._clinica;
		    }
		    set
		    {
		        this._clinica = value;
		    }
		}
		
		private Profesional _profesional;
		public virtual Profesional Profesional 
		{ 
		    get
		    {
		        return this._profesional;
		    }
		    set
		    {
		        this._profesional = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Clinica
	{
		private string _codPostal;
		public virtual string Cod_postal 
		{ 
		    get
		    {
		        return this._codPostal;
		    }
		    set
		    {
		        this._codPostal = value;
		    }
		}
		
		private string _correo;
		public virtual string Correo 
		{ 
		    get
		    {
		        return this._correo;
		    }
		    set
		    {
		        this._correo = value;
		    }
		}
		
		private string _direccion;
		public virtual string Direccion 
		{ 
		    get
		    {
		        return this._direccion;
		    }
		    set
		    {
		        this._direccion = value;
		    }
		}
		
		private int? _idEmpresa;
		public virtual int? Id_empresa 
		{ 
		    get
		    {
		        return this._idEmpresa;
		    }
		    set
		    {
		        this._idEmpresa = value;
		    }
		}
		
		private int _idClinica;
		public virtual int Id_clinica 
		{ 
		    get
		    {
		        return this._idClinica;
		    }
		    set
		    {
		        this._idClinica = value;
		    }
		}
		
		private string _movil;
		public virtual string Movil 
		{ 
		    get
		    {
		        return this._movil;
		    }
		    set
		    {
		        this._movil = value;
		    }
		}
		
		private string _nif;
		public virtual string Nif 
		{ 
		    get
		    {
		        return this._nif;
		    }
		    set
		    {
		        this._nif = value;
		    }
		}
		
		private string _nomClinica;
		public virtual string Nom_clinica 
		{ 
		    get
		    {
		        return this._nomClinica;
		    }
		    set
		    {
		        this._nomClinica = value;
		    }
		}
		
		private string _pais;
		public virtual string Pais 
		{ 
		    get
		    {
		        return this._pais;
		    }
		    set
		    {
		        this._pais = value;
		    }
		}
		
		private string _poblacion;
		public virtual string Poblacion 
		{ 
		    get
		    {
		        return this._poblacion;
		    }
		    set
		    {
		        this._poblacion = value;
		    }
		}
		
		private string _provincia;
		public virtual string Provincia 
		{ 
		    get
		    {
		        return this._provincia;
		    }
		    set
		    {
		        this._provincia = value;
		    }
		}
		
		private string _telefono;
		public virtual string Telefono 
		{ 
		    get
		    {
		        return this._telefono;
		    }
		    set
		    {
		        this._telefono = value;
		    }
		}
		
		private string _urlWeb;
		public virtual string Url_web 
		{ 
		    get
		    {
		        return this._urlWeb;
		    }
		    set
		    {
		        this._urlWeb = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Empresa_sanitaria_clinica> _empresaSanitariaClinicas = new List<Empresa_sanitaria_clinica>();
		public virtual IList<Empresa_sanitaria_clinica> Empresa_sanitaria_clinicas 
		{ 
		    get
		    {
		        return this._empresaSanitariaClinicas;
		    }
		}
		
		private IList<Clinica_profesional> _clinicaProfesionals = new List<Clinica_profesional>();
		public virtual IList<Clinica_profesional> Clinica_profesionals 
		{ 
		    get
		    {
		        return this._clinicaProfesionals;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Cita_diagnostico_asignado
	{
		private int _idCita;
		public virtual int Id_cita 
		{ 
		    get
		    {
		        return this._idCita;
		    }
		    set
		    {
		        this._idCita = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idDiagnosticoAsignado;
		public virtual int? Id_diagnostico_asignado 
		{ 
		    get
		    {
		        return this._idDiagnosticoAsignado;
		    }
		    set
		    {
		        this._idDiagnosticoAsignado = value;
		    }
		}
		
		private Citum _citum;
		public virtual Citum Citum 
		{ 
		    get
		    {
		        return this._citum;
		    }
		    set
		    {
		        this._citum = value;
		    }
		}
		
		private Diagnostico_asignado _diagnosticoAsignado;
		public virtual Diagnostico_asignado Diagnostico_asignado 
		{ 
		    get
		    {
		        return this._diagnosticoAsignado;
		    }
		    set
		    {
		        this._diagnosticoAsignado = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Citum
	{
		private int? _idAgenda;
		public virtual int? Id_agenda 
		{ 
		    get
		    {
		        return this._idAgenda;
		    }
		    set
		    {
		        this._idAgenda = value;
		    }
		}
		
		private string _asunto;
		public virtual string Asunto 
		{ 
		    get
		    {
		        return this._asunto;
		    }
		    set
		    {
		        this._asunto = value;
		    }
		}
		
		private int _duracion;
		public virtual int Duracion 
		{ 
		    get
		    {
		        return this._duracion;
		    }
		    set
		    {
		        this._duracion = value;
		    }
		}
		
		private int _estado;
		public virtual int Estado 
		{ 
		    get
		    {
		        return this._estado;
		    }
		    set
		    {
		        this._estado = value;
		    }
		}
		
		private DateTime _fechaHoraFin;
		public virtual DateTime Fecha_hora_fin 
		{ 
		    get
		    {
		        return this._fechaHoraFin;
		    }
		    set
		    {
		        this._fechaHoraFin = value;
		    }
		}
		
		private DateTime _fechaHoraInicio;
		public virtual DateTime Fecha_hora_inicio 
		{ 
		    get
		    {
		        return this._fechaHoraInicio;
		    }
		    set
		    {
		        this._fechaHoraInicio = value;
		    }
		}
		
		private int _idCita;
		public virtual int Id_cita 
		{ 
		    get
		    {
		        return this._idCita;
		    }
		    set
		    {
		        this._idCita = value;
		    }
		}
		
		private int? _idCitaPadre;
		public virtual int? Id_cita_padre 
		{ 
		    get
		    {
		        return this._idCitaPadre;
		    }
		    set
		    {
		        this._idCitaPadre = value;
		    }
		}
		
		private string _observaciones;
		public virtual string Observaciones 
		{ 
		    get
		    {
		        return this._observaciones;
		    }
		    set
		    {
		        this._observaciones = value;
		    }
		}
		
		private int? _idHistoria;
		public virtual int? Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private int? _idProfesional;
		public virtual int? Id_profesional 
		{ 
		    get
		    {
		        return this._idProfesional;
		    }
		    set
		    {
		        this._idProfesional = value;
		    }
		}
		
		private string _recurrencia;
		public virtual string Recurrencia 
		{ 
		    get
		    {
		        return this._recurrencia;
		    }
		    set
		    {
		        this._recurrencia = value;
		    }
		}
		
		private int? _idTipoCita;
		public virtual int? Id_tipo_cita 
		{ 
		    get
		    {
		        return this._idTipoCita;
		    }
		    set
		    {
		        this._idTipoCita = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private DateTime _llegada;
		public virtual DateTime Llegada 
		{ 
		    get
		    {
		        return this._llegada;
		    }
		    set
		    {
		        this._llegada = value;
		    }
		}
		
		private IList<Cita_diagnostico_asignado> _citaDiagnosticoAsignados = new List<Cita_diagnostico_asignado>();
		public virtual IList<Cita_diagnostico_asignado> Cita_diagnostico_asignados 
		{ 
		    get
		    {
		        return this._citaDiagnosticoAsignados;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Categoria_profesional
	{
		private int _idCategoria;
		public virtual int Id_categoria 
		{ 
		    get
		    {
		        return this._idCategoria;
		    }
		    set
		    {
		        this._idCategoria = value;
		    }
		}
		
		private string _nomCategoria;
		public virtual string Nom_categoria 
		{ 
		    get
		    {
		        return this._nomCategoria;
		    }
		    set
		    {
		        this._nomCategoria = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Base_factura
	{
		private decimal _bimporte;
		public virtual decimal Bimporte 
		{ 
		    get
		    {
		        return this._bimporte;
		    }
		    set
		    {
		        this._bimporte = value;
		    }
		}
		
		private decimal _cimporte;
		public virtual decimal Cimporte 
		{ 
		    get
		    {
		        return this._cimporte;
		    }
		    set
		    {
		        this._cimporte = value;
		    }
		}
		
		private int _idBaseFactura;
		public virtual int Id_base_factura 
		{ 
		    get
		    {
		        return this._idBaseFactura;
		    }
		    set
		    {
		        this._idBaseFactura = value;
		    }
		}
		
		private decimal _importe;
		public virtual decimal Importe 
		{ 
		    get
		    {
		        return this._importe;
		    }
		    set
		    {
		        this._importe = value;
		    }
		}
		
		private float _porcentaje;
		public virtual float Porcentaje 
		{ 
		    get
		    {
		        return this._porcentaje;
		    }
		    set
		    {
		        this._porcentaje = value;
		    }
		}
		
		private int? _idTipoIva;
		public virtual int? Id_tipo_iva 
		{ 
		    get
		    {
		        return this._idTipoIva;
		    }
		    set
		    {
		        this._idTipoIva = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Factura_base_factura> _facturaBaseFacturas = new List<Factura_base_factura>();
		public virtual IList<Factura_base_factura> Factura_base_facturas 
		{ 
		    get
		    {
		        return this._facturaBaseFacturas;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Aseguradora
	{
		private int _idAseguradora;
		public virtual int Id_aseguradora 
		{ 
		    get
		    {
		        return this._idAseguradora;
		    }
		    set
		    {
		        this._idAseguradora = value;
		    }
		}
		
		private string _nomAseguradora;
		public virtual string Nom_aseguradora 
		{ 
		    get
		    {
		        return this._nomAseguradora;
		    }
		    set
		    {
		        this._nomAseguradora = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Antecedente_personal
	{
		private int _idAntecedentePersonal;
		public virtual int Id_antecedente_personal 
		{ 
		    get
		    {
		        return this._idAntecedentePersonal;
		    }
		    set
		    {
		        this._idAntecedentePersonal = value;
		    }
		}
		
		private string _textos;
		public virtual string Textos 
		{ 
		    get
		    {
		        return this._textos;
		    }
		    set
		    {
		        this._textos = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Antecedente_ginecologico
	{
		private string _formulaMenstrual;
		public virtual string Formula_menstrual 
		{ 
		    get
		    {
		        return this._formulaMenstrual;
		    }
		    set
		    {
		        this._formulaMenstrual = value;
		    }
		}
		
		private int _idAntecedenteGinecologico;
		public virtual int Id_antecedente_ginecologico 
		{ 
		    get
		    {
		        return this._idAntecedenteGinecologico;
		    }
		    set
		    {
		        this._idAntecedenteGinecologico = value;
		    }
		}
		
		private string _menarquia;
		public virtual string Menarquia 
		{ 
		    get
		    {
		        return this._menarquia;
		    }
		    set
		    {
		        this._menarquia = value;
		    }
		}
		
		private string _menopausia;
		public virtual string Menopausia 
		{ 
		    get
		    {
		        return this._menopausia;
		    }
		    set
		    {
		        this._menopausia = value;
		    }
		}
		
		private int _nAbortos;
		public virtual int N_abortos 
		{ 
		    get
		    {
		        return this._nAbortos;
		    }
		    set
		    {
		        this._nAbortos = value;
		    }
		}
		
		private int _nPartosCesarea;
		public virtual int N_partos_cesarea 
		{ 
		    get
		    {
		        return this._nPartosCesarea;
		    }
		    set
		    {
		        this._nPartosCesarea = value;
		    }
		}
		
		private int _nPartosEutocicos;
		public virtual int N_partos_eutocicos 
		{ 
		    get
		    {
		        return this._nPartosEutocicos;
		    }
		    set
		    {
		        this._nPartosEutocicos = value;
		    }
		}
		
		private string _textos;
		public virtual string Textos 
		{ 
		    get
		    {
		        return this._textos;
		    }
		    set
		    {
		        this._textos = value;
		    }
		}
		
		private DateTime _ultimaRegla;
		public virtual DateTime Ultima_regla 
		{ 
		    get
		    {
		        return this._ultimaRegla;
		    }
		    set
		    {
		        this._ultimaRegla = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Antecedente_familiar
	{
		private int _idAntecedenteFamiliar;
		public virtual int Id_antecedente_familiar 
		{ 
		    get
		    {
		        return this._idAntecedenteFamiliar;
		    }
		    set
		    {
		        this._idAntecedenteFamiliar = value;
		    }
		}
		
		private string _textos;
		public virtual string Textos 
		{ 
		    get
		    {
		        return this._textos;
		    }
		    set
		    {
		        this._textos = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Analisis_prueba
	{
		private int _idAnalisis;
		public virtual int Id_analisis 
		{ 
		    get
		    {
		        return this._idAnalisis;
		    }
		    set
		    {
		        this._idAnalisis = value;
		    }
		}
		
		private int _seq;
		public virtual int Seq 
		{ 
		    get
		    {
		        return this._seq;
		    }
		    set
		    {
		        this._seq = value;
		    }
		}
		
		private int? _idPrueba;
		public virtual int? Id_prueba 
		{ 
		    get
		    {
		        return this._idPrueba;
		    }
		    set
		    {
		        this._idPrueba = value;
		    }
		}
		
		private Analisi _analisi;
		public virtual Analisi Analisi 
		{ 
		    get
		    {
		        return this._analisi;
		    }
		    set
		    {
		        this._analisi = value;
		    }
		}
		
		private Prueba _prueba;
		public virtual Prueba Prueba 
		{ 
		    get
		    {
		        return this._prueba;
		    }
		    set
		    {
		        this._prueba = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Analisi
	{
		private int _idAnalisis;
		public virtual int Id_analisis 
		{ 
		    get
		    {
		        return this._idAnalisis;
		    }
		    set
		    {
		        this._idAnalisis = value;
		    }
		}
		
		private string _nomAnalisis;
		public virtual string Nom_analisis 
		{ 
		    get
		    {
		        return this._nomAnalisis;
		    }
		    set
		    {
		        this._nomAnalisis = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Analisis_prueba> _analisisPruebas = new List<Analisis_prueba>();
		public virtual IList<Analisis_prueba> Analisis_pruebas 
		{ 
		    get
		    {
		        return this._analisisPruebas;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Agenda
	{
		private DateTime _horaFin;
		public virtual DateTime Hora_fin 
		{ 
		    get
		    {
		        return this._horaFin;
		    }
		    set
		    {
		        this._horaFin = value;
		    }
		}
		
		private DateTime _horaInicio;
		public virtual DateTime Hora_inicio 
		{ 
		    get
		    {
		        return this._horaInicio;
		    }
		    set
		    {
		        this._horaInicio = value;
		    }
		}
		
		private int _idAgenda;
		public virtual int Id_agenda 
		{ 
		    get
		    {
		        return this._idAgenda;
		    }
		    set
		    {
		        this._idAgenda = value;
		    }
		}
		
		private string _nomAgenda;
		public virtual string Nom_agenda 
		{ 
		    get
		    {
		        return this._nomAgenda;
		    }
		    set
		    {
		        this._nomAgenda = value;
		    }
		}
		
		private int _tramo;
		public virtual int Tramo 
		{ 
		    get
		    {
		        return this._tramo;
		    }
		    set
		    {
		        this._tramo = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Acto_medico_asg
	{
		private int? _idActoMedicoAsc;
		public virtual int? Id_acto_medico_asc 
		{ 
		    get
		    {
		        return this._idActoMedicoAsc;
		    }
		    set
		    {
		        this._idActoMedicoAsc = value;
		    }
		}
		
		private bool _comunicado;
		public virtual bool Comunicado 
		{ 
		    get
		    {
		        return this._comunicado;
		    }
		    set
		    {
		        this._comunicado = value;
		    }
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private int _idActoMedicoAsg;
		public virtual int Id_acto_medico_asg 
		{ 
		    get
		    {
		        return this._idActoMedicoAsg;
		    }
		    set
		    {
		        this._idActoMedicoAsg = value;
		    }
		}
		
		private string _observaciones;
		public virtual string Observaciones 
		{ 
		    get
		    {
		        return this._observaciones;
		    }
		    set
		    {
		        this._observaciones = value;
		    }
		}
		
		private int? _idHistoria;
		public virtual int? Id_historia 
		{ 
		    get
		    {
		        return this._idHistoria;
		    }
		    set
		    {
		        this._idHistoria = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
		private IList<Historial_acto_medico_asg> _historialActoMedicoAsgs = new List<Historial_acto_medico_asg>();
		public virtual IList<Historial_acto_medico_asg> Historial_acto_medico_asgs 
		{ 
		    get
		    {
		        return this._historialActoMedicoAsgs;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Acto_medico_asc
	{
		private int? _idActoMedico;
		public virtual int? Id_acto_medico 
		{ 
		    get
		    {
		        return this._idActoMedico;
		    }
		    set
		    {
		        this._idActoMedico = value;
		    }
		}
		
		private int? _idAseguradora;
		public virtual int? Id_aseguradora 
		{ 
		    get
		    {
		        return this._idAseguradora;
		    }
		    set
		    {
		        this._idAseguradora = value;
		    }
		}
		
		private int _idActoMedicoAsc;
		public virtual int Id_acto_medico_asc 
		{ 
		    get
		    {
		        return this._idActoMedicoAsc;
		    }
		    set
		    {
		        this._idActoMedicoAsc = value;
		    }
		}
		
		private decimal _importe;
		public virtual decimal Importe 
		{ 
		    get
		    {
		        return this._importe;
		    }
		    set
		    {
		        this._importe = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}

namespace RidocciModel	
{
	public partial class Acto_medico
	{
		private int _idActoMedico;
		public virtual int Id_acto_medico 
		{ 
		    get
		    {
		        return this._idActoMedico;
		    }
		    set
		    {
		        this._idActoMedico = value;
		    }
		}
		
		private string _nomActoMedico;
		public virtual string Nom_acto_medico 
		{ 
		    get
		    {
		        return this._nomActoMedico;
		    }
		    set
		    {
		        this._nomActoMedico = value;
		    }
		}
		
		private short _voaVersion;
		public virtual short Voa_version 
		{ 
		    get
		    {
		        return this._voaVersion;
		    }
		    set
		    {
		        this._voaVersion = value;
		    }
		}
		
	}
}
#pragma warning restore 1591

