//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadGrid {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadGrid.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string AddNewRecordImageUrl {
            get {
                return ResourceManager.GetString("AddNewRecordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo regsitro.
        /// </summary>
        internal static string AddNewRecordText {
            get {
                return ResourceManager.GetString("AddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entre.
        /// </summary>
        internal static string BetweenText {
            get {
                return ResourceManager.GetString("BetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño página:.
        /// </summary>
        internal static string ChangePageSizeLabelText {
            get {
                return ResourceManager.GetString("ChangePageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        internal static string ChangePageSizeLinkButtonText {
            get {
                return ResourceManager.GetString("ChangePageSizeLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colapsar grupo.
        /// </summary>
        internal static string CollapseTooltip {
            get {
                return ResourceManager.GetString("CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho: &lt;strong&gt;{0}&lt;/strong&gt; &lt;em&gt;pixels&lt;/em&gt;.
        /// </summary>
        internal static string ColumnResizeTooltipFormatString {
            get {
                return ResourceManager.GetString("ColumnResizeTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contiene.
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoContiene.
        /// </summary>
        internal static string DoesNotContainText {
            get {
                return ResourceManager.GetString("DoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre a grupo o reordene.
        /// </summary>
        internal static string DragToGroupOrReorder {
            get {
                return ResourceManager.GetString("DragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre para cambiar tamaño.
        /// </summary>
        internal static string DragToResize {
            get {
                return ResourceManager.GetString("DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drop here to reorder.
        /// </summary>
        internal static string DropHereToReorder {
            get {
                return ResourceManager.GetString("DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Termina con.
        /// </summary>
        internal static string EndsWithText {
            get {
                return ResourceManager.GetString("EndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Igual a.
        /// </summary>
        internal static string EqualToText {
            get {
                return ResourceManager.GetString("EqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expamdir grupo.
        /// </summary>
        internal static string ExpandTooltip {
            get {
                return ResourceManager.GetString("ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ExportToCsvImageUrl {
            get {
                return ResourceManager.GetString("ExportToCsvImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar CSV.
        /// </summary>
        internal static string ExportToCsvText {
            get {
                return ResourceManager.GetString("ExportToCsvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ExportToExcelImageUrl {
            get {
                return ResourceManager.GetString("ExportToExcelImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Excel.
        /// </summary>
        internal static string ExportToExcelText {
            get {
                return ResourceManager.GetString("ExportToExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ExportToPdfImageUrl {
            get {
                return ResourceManager.GetString("ExportToPdfImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar PDF.
        /// </summary>
        internal static string ExportToPdfText {
            get {
                return ResourceManager.GetString("ExportToPdfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ExportToWordImageUrl {
            get {
                return ResourceManager.GetString("ExportToWordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Word.
        /// </summary>
        internal static string ExportToWordText {
            get {
                return ResourceManager.GetString("ExportToWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string FilterExpression {
            get {
                return ResourceManager.GetString("FilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        internal static string FilterImageToolTip {
            get {
                return ResourceManager.GetString("FilterImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera página.
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagina:.
        /// </summary>
        internal static string GoToPageLabelText {
            get {
                return ResourceManager.GetString("GoToPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir.
        /// </summary>
        internal static string GoToPageLinkButtonText {
            get {
                return ResourceManager.GetString("GoToPageLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor o igual que.
        /// </summary>
        internal static string GreaterThanOrEqualToText {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor que.
        /// </summary>
        internal static string GreaterThanText {
            get {
                return ResourceManager.GetString("GreaterThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ; .
        /// </summary>
        internal static string GroupByFieldsSeparator {
            get {
                return ResourceManager.GetString("GroupByFieldsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ... grupo continua de la página anterior..
        /// </summary>
        internal static string GroupContinuedFormatString {
            get {
                return ResourceManager.GetString("GroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo continua en la página siguiente..
        /// </summary>
        internal static string GroupContinuesFormatString {
            get {
                return ResourceManager.GetString("GroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre y suelte una cabecera para agrupar..
        /// </summary>
        internal static string GroupPanelText {
            get {
                return ResourceManager.GetString("GroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando {0} de  {1} elementos..
        /// </summary>
        internal static string GroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("GroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  ({0}).
        /// </summary>
        internal static string GroupSplitFormat {
            get {
                return ResourceManager.GetString("GroupSplitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string HeaderContextMenuAggregates {
            get {
                return ResourceManager.GetString("HeaderContextMenuAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string HeaderContextMenuAndLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuAndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        internal static string HeaderContextMenuAvgAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuAvgAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor.
        /// </summary>
        internal static string HeaderContextMenuBestFitText {
            get {
                return ResourceManager.GetString("HeaderContextMenuBestFitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar filtro.
        /// </summary>
        internal static string HeaderContextMenuClearButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas.
        /// </summary>
        internal static string HeaderContextMenuColumns {
            get {
                return ResourceManager.GetString("HeaderContextMenuColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contar.
        /// </summary>
        internal static string HeaderContextMenuCountAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contar distintos.
        /// </summary>
        internal static string HeaderContextMenuCountDistinctAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountDistinctAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        internal static string HeaderContextMenuCustomAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCustomAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        internal static string HeaderContextMenuFilterButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        internal static string HeaderContextMenuFilterItemText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Priemro.
        /// </summary>
        internal static string HeaderContextMenuFirstAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFirstAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupado por.
        /// </summary>
        internal static string HeaderContextMenuGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último.
        /// </summary>
        internal static string HeaderContextMenuLastAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuLastAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max.
        /// </summary>
        internal static string HeaderContextMenuMaxAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMaxAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Min.
        /// </summary>
        internal static string HeaderContextMenuMinAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMinAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno.
        /// </summary>
        internal static string HeaderContextMenuNoneAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuNoneAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra filas con valor....
        /// </summary>
        internal static string HeaderContextMenuRowsLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar asc..
        /// </summary>
        internal static string HeaderContextMenuSortAsc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpia orden.
        /// </summary>
        internal static string HeaderContextMenuSortClear {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar des..
        /// </summary>
        internal static string HeaderContextMenuSortDesc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sum.
        /// </summary>
        internal static string HeaderContextMenuSumAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuSumAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desagrupar.
        /// </summary>
        internal static string HeaderContextMenuUnGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuUnGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string HierarchyCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchyCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expandir.
        /// </summary>
        internal static string HierarchyExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchyExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collapsar autoreferencia.
        /// </summary>
        internal static string HierarchySelfCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expandir autoreferencia.
        /// </summary>
        internal static string HierarchySelfExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está vacio.
        /// </summary>
        internal static string IsEmptyText {
            get {
                return ResourceManager.GetString("IsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es nulo.
        /// </summary>
        internal static string IsNullText {
            get {
                return ResourceManager.GetString("IsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última página.
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor o igual que.
        /// </summary>
        internal static string LessThanOrEqualToText {
            get {
                return ResourceManager.GetString("LessThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor que.
        /// </summary>
        internal static string LessThanText {
            get {
                return ResourceManager.GetString("LessThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Páginas siguientes.
        /// </summary>
        internal static string NextPagesToolTip {
            get {
                return ResourceManager.GetString("NextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página siguiente.
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros hijos que mostrar.
        /// </summary>
        internal static string NoDetailRecordsText {
            get {
                return ResourceManager.GetString("NoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin filtro.
        /// </summary>
        internal static string NoFilterText {
            get {
                return ResourceManager.GetString("NoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros que mostrar..
        /// </summary>
        internal static string NoMasterRecordsText {
            get {
                return ResourceManager.GetString("NoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entre..
        /// </summary>
        internal static string NotBetweenText {
            get {
                return ResourceManager.GetString("NotBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No igual a .
        /// </summary>
        internal static string NotEqualToText {
            get {
                return ResourceManager.GetString("NotEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está vacío.
        /// </summary>
        internal static string NotIsEmptyText {
            get {
                return ResourceManager.GetString("NotIsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es nulo.
        /// </summary>
        internal static string NotIsNullText {
            get {
                return ResourceManager.GetString("NotIsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de {0}.
        /// </summary>
        internal static string PageOfLabelText {
            get {
                return ResourceManager.GetString("PageOfLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambia página: {4} &amp;nbsp;Página &lt;strong&gt;{0}&lt;/strong&gt; de &lt;strong&gt;{1}&lt;/strong&gt;, elementos &lt;strong&gt;{2}&lt;/strong&gt; de &lt;strong&gt;{3}&lt;/strong&gt; de &lt;strong&gt;{5}&lt;/strong&gt;..
        /// </summary>
        internal static string PagerTextFormat {
            get {
                return ResourceManager.GetString("PagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página &lt;strong&gt;{0}&lt;/strong&gt; de &lt;strong&gt;{1}&lt;/strong&gt;.
        /// </summary>
        internal static string PagerTooltipFormatString {
            get {
                return ResourceManager.GetString("PagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño página:.
        /// </summary>
        internal static string PageSizeLabelText {
            get {
                return ResourceManager.GetString("PageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página anterior.
        /// </summary>
        internal static string PrevPagesToolTip {
            get {
                return ResourceManager.GetString("PrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página anterior.
        /// </summary>
        internal static string PrevPageToolTip {
            get {
                return ResourceManager.GetString("PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string RefreshImageUrl {
            get {
                return ResourceManager.GetString("RefreshImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No elimine esta clave..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenado asc.
        /// </summary>
        internal static string SortedAscToolTip {
            get {
                return ResourceManager.GetString("SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenado desc.
        /// </summary>
        internal static string SortedDescToolTip {
            get {
                return ResourceManager.GetString("SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clic aqui para ordenar.
        /// </summary>
        internal static string SortToolTip {
            get {
                return ResourceManager.GetString("SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza con.
        /// </summary>
        internal static string StartsWithText {
            get {
                return ResourceManager.GetString("StartsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        internal static string StatusReadyText {
            get {
                return ResourceManager.GetString("StatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clic aquí para desagrupar..
        /// </summary>
        internal static string UnGroupButtonTooltip {
            get {
                return ResourceManager.GetString("UnGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre fuera de la barra para desagrupar.
        /// </summary>
        internal static string UnGroupTooltip {
            get {
                return ResourceManager.GetString("UnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
    }
}
