#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace AriCliModel	
{
	public partial class Address
	{
		private string street2;
		public virtual string Street2 
		{ 
		    get
		    {
		        return this.street2;
		    }
		    set
		    {
		        this.street2 = value;
		    }
		}
		
		private string street;
		public virtual string Street 
		{ 
		    get
		    {
		        return this.street;
		    }
		    set
		    {
		        this.street = value;
		    }
		}
		
		private string postCode;
		public virtual string PostCode 
		{ 
		    get
		    {
		        return this.postCode;
		    }
		    set
		    {
		        this.postCode = value;
		    }
		}
		
		private string country;
		public virtual string Country 
		{ 
		    get
		    {
		        return this.country;
		    }
		    set
		    {
		        this.country = value;
		    }
		}
		
		private string city;
		public virtual string City 
		{ 
		    get
		    {
		        return this.city;
		    }
		    set
		    {
		        this.city = value;
		    }
		}
		
		private int addressId;
		public virtual int AddressId 
		{ 
		    get
		    {
		        return this.addressId;
		    }
		    set
		    {
		        this.addressId = value;
		    }
		}
		
		private string type;
		public virtual string Type 
		{ 
		    get
		    {
		        return this.type;
		    }
		    set
		    {
		        this.type = value;
		    }
		}
		
		private string province;
		public virtual string Province 
		{ 
		    get
		    {
		        return this.province;
		    }
		    set
		    {
		        this.province = value;
		    }
		}
		
		private HealthcareCompany healthcareCompany;
		public virtual HealthcareCompany HealthcareCompany 
		{ 
		    get
		    {
		        return this.healthcareCompany;
		    }
		    set
		    {
		        this.healthcareCompany = value;
		    }
		}
		
		private Clinic clinic;
		public virtual Clinic Clinic 
		{ 
		    get
		    {
		        return this.clinic;
		    }
		    set
		    {
		        this.clinic = value;
		    }
		}
		
		private Person person;
		public virtual Person Person 
		{ 
		    get
		    {
		        return this.person;
		    }
		    set
		    {
		        this.person = value;
		    }
		}
		
	}
}
