#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public partial class AnestheticServiceNote
	{
		private int anestheticServiceNoteId;
		public virtual int AnestheticServiceNoteId 
		{ 
		    get
		    {
		        return this.anestheticServiceNoteId;
		    }
		    set
		    {
		        this.anestheticServiceNoteId = value;
		    }
		}
		
		private DateTime serviceNoteDate;
		public virtual DateTime ServiceNoteDate 
		{ 
		    get
		    {
		        return this.serviceNoteDate;
		    }
		    set
		    {
		        this.serviceNoteDate = value;
		    }
		}
		
		private decimal total;
		public virtual decimal Total 
		{ 
		    get
		    {
		        return this.total;
		    }
		    set
		    {
		        this.total = value;
		    }
		}
		
		private bool chk1;
		public virtual bool Chk1 
		{ 
		    get
		    {
		        return this.chk1;
		    }
		    set
		    {
		        this.chk1 = value;
		    }
		}
		
		private bool chk2;
		public virtual bool Chk2 
		{ 
		    get
		    {
		        return this.chk2;
		    }
		    set
		    {
		        this.chk2 = value;
		    }
		}
		
		private User user;
		public virtual User User 
		{ 
		    get
		    {
		        return this.user;
		    }
		    set
		    {
		        this.user = value;
		    }
		}
		
		private Clinic clinic;
		public virtual Clinic Clinic 
		{ 
		    get
		    {
		        return this.clinic;
		    }
		    set
		    {
		        this.clinic = value;
		    }
		}
		
		private Professional professional;
		public virtual Professional Professional 
		{ 
		    get
		    {
		        return this.professional;
		    }
		    set
		    {
		        this.professional = value;
		    }
		}
		
		private Professional surgeon;
		public virtual Professional Surgeon 
		{ 
		    get
		    {
		        return this.surgeon;
		    }
		    set
		    {
		        this.surgeon = value;
		    }
		}
		
		private Customer customer;
		public virtual Customer Customer 
		{ 
		    get
		    {
		        return this.customer;
		    }
		    set
		    {
		        this.customer = value;
		    }
		}
		
		private IList<Procedure> procedures = new List<Procedure>();
		public virtual IList<Procedure> Procedures 
		{ 
		    get
		    {
		        return this.procedures;
		    }
		}
		
		private IList<AnestheticTicket> anestheticTickets = new List<AnestheticTicket>();
		public virtual IList<AnestheticTicket> AnestheticTickets 
		{ 
		    get
		    {
		        return this.anestheticTickets;
		    }
		}
		
	}
}
