#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public interface BasicOpticalTest
	{
		decimal CloseVisualAcuityRightEye 
		{ 
			get;
			set;
		}
		decimal CloseVisualAcuityLeftEye 
		{ 
			get;
			set;
		}
		decimal CloseVisualAcuityBothEyes 
		{ 
			get;
			set;
		}
		decimal FarVisualAcuityRightEye 
		{ 
			get;
			set;
		}
		decimal FarVisualAcuityLeftEye 
		{ 
			get;
			set;
		}
		decimal FarVisualAcuityBothEyes 
		{ 
			get;
			set;
		}
	}
}
