#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriCliModel;

namespace AriCliModel	
{
	public partial class Customer : Person
	{
		private string comercialName;
		public virtual string ComercialName
		{
			get
			{
				return this.comercialName;
			}
			set
			{
				this.comercialName = value;
			}
		}
		
		private string vATIN;
		public virtual string VATIN
		{
			get
			{
				return this.vATIN;
			}
			set
			{
				this.vATIN = value;
			}
		}
		
		private int oftId;
		public virtual int OftId
		{
			get
			{
				return this.oftId;
			}
			set
			{
				this.oftId = value;
			}
		}
		
		private IList<AnestheticServiceNote> anestheticServiceNotes = new List<AnestheticServiceNote>();
		public virtual IList<AnestheticServiceNote> AnestheticServiceNotes
		{
			get
			{
				return this.anestheticServiceNotes;
			}
		}
		
		private IList<Invoice> invoices = new List<Invoice>();
		public virtual IList<Invoice> Invoices
		{
			get
			{
				return this.invoices;
			}
		}
		
		private IList<Policy> policies1 = new List<Policy>();
		public virtual IList<Policy> Policies
		{
			get
			{
				return this.policies1;
			}
		}
		
		private IList<Patient> patients = new List<Patient>();
		public virtual IList<Patient> Patients
		{
			get
			{
				return this.patients;
			}
		}
		
		private IList<ServiceNote> serviceNotes = new List<ServiceNote>();
		public virtual IList<ServiceNote> ServiceNotes
		{
			get
			{
				return this.serviceNotes;
			}
		}
		
	}
}
#pragma warning restore 1591
