#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriCliModel;

namespace AriCliModel	
{
	public partial class EstimateLine
	{
		private int estimateLineId;
		public virtual int EstimateLineId
		{
			get
			{
				return this.estimateLineId;
			}
			set
			{
				this.estimateLineId = value;
			}
		}
		
		private decimal amount;
		public virtual decimal Amount
		{
			get
			{
				return this.amount;
			}
			set
			{
				this.amount = value;
			}
		}
		
		private decimal discount;
		public virtual decimal Discount
		{
			get
			{
				return this.discount;
			}
			set
			{
				this.discount = value;
			}
		}
		
		private string description;
		public virtual string Description
		{
			get
			{
				return this.description;
			}
			set
			{
				this.description = value;
			}
		}
		
		private InsuranceService insuranceService;
		public virtual InsuranceService InsuranceService
		{
			get
			{
				return this.insuranceService;
			}
			set
			{
				this.insuranceService = value;
			}
		}
		
		private Estimate estimate;
		public virtual Estimate Estimate
		{
			get
			{
				return this.estimate;
			}
			set
			{
				this.estimate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
