#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace AriCliModel	
{
	public partial class External_invoice
	{
		private int? personId;
		public virtual int? Person_id 
		{ 
		    get
		    {
		        return this.personId;
		    }
		    set
		    {
		        this.personId = value;
		    }
		}
		
		private int invoiceId;
		public virtual int Invoice_id 
		{ 
		    get
		    {
		        return this.invoiceId;
		    }
		    set
		    {
		        this.invoiceId = value;
		    }
		}
		
		private Professional professional;
		public virtual Professional Professional 
		{ 
		    get
		    {
		        return this.professional;
		    }
		    set
		    {
		        this.professional = value;
		    }
		}
		
		private Invoice invoice;
		public virtual Invoice Invoice 
		{ 
		    get
		    {
		        return this.invoice;
		    }
		    set
		    {
		        this.invoice = value;
		    }
		}
		
		private IList<ExternalInvoiceLine> externalInvoiceLines = new List<ExternalInvoiceLine>();
		public virtual IList<ExternalInvoiceLine> ExternalInvoiceLines 
		{ 
		    get
		    {
		        return this.externalInvoiceLines;
		    }
		}
		
	}
}
