#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public partial class Fundus
	{
		private int id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.id;
		    }
		    set
		    {
		        this.id = value;
		    }
		}
		
		private string opticNerve;
		public virtual string OpticNerve 
		{ 
		    get
		    {
		        return this.opticNerve;
		    }
		    set
		    {
		        this.opticNerve = value;
		    }
		}
		
		private string vessels;
		public virtual string Vessels 
		{ 
		    get
		    {
		        return this.vessels;
		    }
		    set
		    {
		        this.vessels = value;
		    }
		}
		
		private string macula;
		public virtual string Macula 
		{ 
		    get
		    {
		        return this.macula;
		    }
		    set
		    {
		        this.macula = value;
		    }
		}
		
		private string vitreous;
		public virtual string Vitreous 
		{ 
		    get
		    {
		        return this.vitreous;
		    }
		    set
		    {
		        this.vitreous = value;
		    }
		}
		
		private string periphery;
		public virtual string Periphery 
		{ 
		    get
		    {
		        return this.periphery;
		    }
		    set
		    {
		        this.periphery = value;
		    }
		}
		
		private OphthalmologicVisit ophthalmologicVisit;
		public virtual OphthalmologicVisit OphthalmologicVisit 
		{ 
		    get
		    {
		        return this.ophthalmologicVisit;
		    }
		    set
		    {
		        this.ophthalmologicVisit = value;
		    }
		}
		
	}
}
