#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public partial class GlassesTest : OpticalTest
	{
		private int id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.id;
		    }
		    set
		    {
		        this.id = value;
		    }
		}
		
		private string comments;
		public virtual string Comments 
		{ 
		    get
		    {
		        return this.comments;
		    }
		    set
		    {
		        this.comments = value;
		    }
		}
		
		private decimal farSphericityRightEye;
		public virtual decimal FarSphericityRightEye 
		{ 
		    get
		    {
		        return this.farSphericityRightEye;
		    }
		    set
		    {
		        this.farSphericityRightEye = value;
		    }
		}
		
		private decimal farCylinderRightEye;
		public virtual decimal FarCylinderRightEye 
		{ 
		    get
		    {
		        return this.farCylinderRightEye;
		    }
		    set
		    {
		        this.farCylinderRightEye = value;
		    }
		}
		
		private decimal farAxisRightEye;
		public virtual decimal FarAxisRightEye 
		{ 
		    get
		    {
		        return this.farAxisRightEye;
		    }
		    set
		    {
		        this.farAxisRightEye = value;
		    }
		}
		
		private decimal farPrimsRightEye;
		public virtual decimal FarPrimsRightEye 
		{ 
		    get
		    {
		        return this.farPrimsRightEye;
		    }
		    set
		    {
		        this.farPrimsRightEye = value;
		    }
		}
		
		private decimal farVisualAcuityRightEye;
		public virtual decimal FarVisualAcuityRightEye 
		{ 
		    get
		    {
		        return this.farVisualAcuityRightEye;
		    }
		    set
		    {
		        this.farVisualAcuityRightEye = value;
		    }
		}
		
		private decimal farSphericityLeftEye;
		public virtual decimal FarSphericityLeftEye 
		{ 
		    get
		    {
		        return this.farSphericityLeftEye;
		    }
		    set
		    {
		        this.farSphericityLeftEye = value;
		    }
		}
		
		private decimal farCylinderLeftEye;
		public virtual decimal FarCylinderLeftEye 
		{ 
		    get
		    {
		        return this.farCylinderLeftEye;
		    }
		    set
		    {
		        this.farCylinderLeftEye = value;
		    }
		}
		
		private decimal farAxisLeftEye;
		public virtual decimal FarAxisLeftEye 
		{ 
		    get
		    {
		        return this.farAxisLeftEye;
		    }
		    set
		    {
		        this.farAxisLeftEye = value;
		    }
		}
		
		private decimal farPrismLeftEye;
		public virtual decimal FarPrismLeftEye 
		{ 
		    get
		    {
		        return this.farPrismLeftEye;
		    }
		    set
		    {
		        this.farPrismLeftEye = value;
		    }
		}
		
		private decimal farVisualAcuityLeftEye;
		public virtual decimal FarVisualAcuityLeftEye 
		{ 
		    get
		    {
		        return this.farVisualAcuityLeftEye;
		    }
		    set
		    {
		        this.farVisualAcuityLeftEye = value;
		    }
		}
		
		private decimal closeSphericityRightEye;
		public virtual decimal CloseSphericityRightEye 
		{ 
		    get
		    {
		        return this.closeSphericityRightEye;
		    }
		    set
		    {
		        this.closeSphericityRightEye = value;
		    }
		}
		
		private decimal closeSphericityLeftEye;
		public virtual decimal CloseSphericityLeftEye 
		{ 
		    get
		    {
		        return this.closeSphericityLeftEye;
		    }
		    set
		    {
		        this.closeSphericityLeftEye = value;
		    }
		}
		
		private string closeSphericityCenters;
		public virtual string CloseSphericityCenters 
		{ 
		    get
		    {
		        return this.closeSphericityCenters;
		    }
		    set
		    {
		        this.closeSphericityCenters = value;
		    }
		}
		
		private decimal closeCylinderRightEye;
		public virtual decimal CloseCylinderRightEye 
		{ 
		    get
		    {
		        return this.closeCylinderRightEye;
		    }
		    set
		    {
		        this.closeCylinderRightEye = value;
		    }
		}
		
		private decimal closeCylinderLeftEye;
		public virtual decimal CloseCylinderLeftEye 
		{ 
		    get
		    {
		        return this.closeCylinderLeftEye;
		    }
		    set
		    {
		        this.closeCylinderLeftEye = value;
		    }
		}
		
		private decimal closeAxisRightEye;
		public virtual decimal CloseAxisRightEye 
		{ 
		    get
		    {
		        return this.closeAxisRightEye;
		    }
		    set
		    {
		        this.closeAxisRightEye = value;
		    }
		}
		
		private decimal closeAxisLeftEye;
		public virtual decimal CloseAxisLeftEye 
		{ 
		    get
		    {
		        return this.closeAxisLeftEye;
		    }
		    set
		    {
		        this.closeAxisLeftEye = value;
		    }
		}
		
		private decimal closePrismRightEye;
		public virtual decimal ClosePrismRightEye 
		{ 
		    get
		    {
		        return this.closePrismRightEye;
		    }
		    set
		    {
		        this.closePrismRightEye = value;
		    }
		}
		
		private decimal closePrismLeftEye;
		public virtual decimal ClosePrismLeftEye 
		{ 
		    get
		    {
		        return this.closePrismLeftEye;
		    }
		    set
		    {
		        this.closePrismLeftEye = value;
		    }
		}
		
		private decimal closeAcuityRightEye;
		public virtual decimal CloseAcuityRightEye 
		{ 
		    get
		    {
		        return this.closeAcuityRightEye;
		    }
		    set
		    {
		        this.closeAcuityRightEye = value;
		    }
		}
		
		private decimal closeAcuityLeftEye;
		public virtual decimal CloseAcuityLeftEye 
		{ 
		    get
		    {
		        return this.closeAcuityLeftEye;
		    }
		    set
		    {
		        this.closeAcuityLeftEye = value;
		    }
		}
		
		private decimal bothSphericityRightEye;
		public virtual decimal BothSphericityRightEye 
		{ 
		    get
		    {
		        return this.bothSphericityRightEye;
		    }
		    set
		    {
		        this.bothSphericityRightEye = value;
		    }
		}
		
		private decimal bothSphericityLeftEye;
		public virtual decimal BothSphericityLeftEye 
		{ 
		    get
		    {
		        return this.bothSphericityLeftEye;
		    }
		    set
		    {
		        this.bothSphericityLeftEye = value;
		    }
		}
		
		private decimal bothCylinderRightEye;
		public virtual decimal BothCylinderRightEye 
		{ 
		    get
		    {
		        return this.bothCylinderRightEye;
		    }
		    set
		    {
		        this.bothCylinderRightEye = value;
		    }
		}
		
		private decimal bothCylinderLeftEye;
		public virtual decimal BothCylinderLeftEye 
		{ 
		    get
		    {
		        return this.bothCylinderLeftEye;
		    }
		    set
		    {
		        this.bothCylinderLeftEye = value;
		    }
		}
		
		private decimal bothAxisRightEye;
		public virtual decimal BothAxisRightEye 
		{ 
		    get
		    {
		        return this.bothAxisRightEye;
		    }
		    set
		    {
		        this.bothAxisRightEye = value;
		    }
		}
		
		private decimal bothAxisLeftEye;
		public virtual decimal BothAxisLeftEye 
		{ 
		    get
		    {
		        return this.bothAxisLeftEye;
		    }
		    set
		    {
		        this.bothAxisLeftEye = value;
		    }
		}
		
		private decimal bothPrismRightEye;
		public virtual decimal BothPrismRightEye 
		{ 
		    get
		    {
		        return this.bothPrismRightEye;
		    }
		    set
		    {
		        this.bothPrismRightEye = value;
		    }
		}
		
		private decimal bothPrismLeftEye;
		public virtual decimal BothPrismLeftEye 
		{ 
		    get
		    {
		        return this.bothPrismLeftEye;
		    }
		    set
		    {
		        this.bothPrismLeftEye = value;
		    }
		}
		
		private decimal bothAcuityRightEye;
		public virtual decimal BothAcuityRightEye 
		{ 
		    get
		    {
		        return this.bothAcuityRightEye;
		    }
		    set
		    {
		        this.bothAcuityRightEye = value;
		    }
		}
		
		private decimal bothAcuityLeftEye;
		public virtual decimal BothAcuityLeftEye 
		{ 
		    get
		    {
		        return this.bothAcuityLeftEye;
		    }
		    set
		    {
		        this.bothAcuityLeftEye = value;
		    }
		}
		
		private decimal farCenters;
		public virtual decimal FarCenters 
		{ 
		    get
		    {
		        return this.farCenters;
		    }
		    set
		    {
		        this.farCenters = value;
		    }
		}
		
		private decimal closeCenters;
		public virtual decimal CloseCenters 
		{ 
		    get
		    {
		        return this.closeCenters;
		    }
		    set
		    {
		        this.closeCenters = value;
		    }
		}
		
		private decimal bothCenters;
		public virtual decimal BothCenters 
		{ 
		    get
		    {
		        return this.bothCenters;
		    }
		    set
		    {
		        this.bothCenters = value;
		    }
		}
		
		private decimal farAcuity;
		public virtual decimal FarAcuity 
		{ 
		    get
		    {
		        return this.farAcuity;
		    }
		    set
		    {
		        this.farAcuity = value;
		    }
		}
		
		private decimal closeAcuity;
		public virtual decimal CloseAcuity 
		{ 
		    get
		    {
		        return this.closeAcuity;
		    }
		    set
		    {
		        this.closeAcuity = value;
		    }
		}
		
		private decimal bothAcuity;
		public virtual decimal BothAcuity 
		{ 
		    get
		    {
		        return this.bothAcuity;
		    }
		    set
		    {
		        this.bothAcuity = value;
		    }
		}
		
		private Refractometry refractometry;
		public virtual Refractometry Refractometry 
		{ 
		    get
		    {
		        return this.refractometry;
		    }
		    set
		    {
		        this.refractometry = value;
		    }
		}
		
	}
}
