#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriCliModel;

namespace AriCliModel	
{
	public partial class OphthalmologicVisit : BaseVisit
	{
		private string diagnosticDetails;
		public virtual string DiagnosticDetails
		{
			get
			{
				return this.diagnosticDetails;
			}
			set
			{
				this.diagnosticDetails = value;
			}
		}
		
		private IList<AntSegment> antSegments = new List<AntSegment>();
		public virtual IList<AntSegment> AntSegments
		{
			get
			{
				return this.antSegments;
			}
		}
		
		private IList<MotAppend> motAppends = new List<MotAppend>();
		public virtual IList<MotAppend> MotAppends
		{
			get
			{
				return this.motAppends;
			}
		}
		
		private IList<Fundus> fundus = new List<Fundus>();
		public virtual IList<Fundus> Fundus
		{
			get
			{
				return this.fundus;
			}
		}
		
	}
}
#pragma warning restore 1591
