#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public partial class Parameter
	{
		private int parameterId;
		public virtual int ParameterId 
		{ 
		    get
		    {
		        return this.parameterId;
		    }
		    set
		    {
		        this.parameterId = value;
		    }
		}
		
		private bool useNomenclator;
		public virtual bool UseNomenclator 
		{ 
		    get
		    {
		        return this.useNomenclator;
		    }
		    set
		    {
		        this.useNomenclator = value;
		    }
		}
		
		private Service painPump;
		public virtual Service PainPump 
		{ 
		    get
		    {
		        return this.painPump;
		    }
		    set
		    {
		        this.painPump = value;
		    }
		}
		
	}
}
