#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public partial class Policy
	{
		private int policyId;
		public virtual int PolicyId 
		{ 
		    get
		    {
		        return this.policyId;
		    }
		    set
		    {
		        this.policyId = value;
		    }
		}
		
		private string policyNumber;
		public virtual string PolicyNumber 
		{ 
		    get
		    {
		        return this.policyNumber;
		    }
		    set
		    {
		        this.policyNumber = value;
		    }
		}
		
		private DateTime beginDate;
		public virtual DateTime BeginDate 
		{ 
		    get
		    {
		        return this.beginDate;
		    }
		    set
		    {
		        this.beginDate = value;
		    }
		}
		
		private DateTime endDate;
		public virtual DateTime EndDate 
		{ 
		    get
		    {
		        return this.endDate;
		    }
		    set
		    {
		        this.endDate = value;
		    }
		}
		
		private string type;
		public virtual string Type 
		{ 
		    get
		    {
		        return this.type;
		    }
		    set
		    {
		        this.type = value;
		    }
		}
		
		private Insurance insurance;
		public virtual Insurance Insurance 
		{ 
		    get
		    {
		        return this.insurance;
		    }
		    set
		    {
		        this.insurance = value;
		    }
		}
		
		private Customer customer;
		public virtual Customer Customer 
		{ 
		    get
		    {
		        return this.customer;
		    }
		    set
		    {
		        this.customer = value;
		    }
		}
		
		private IList<Ticket> tickets = new List<Ticket>();
		public virtual IList<Ticket> Tickets 
		{ 
		    get
		    {
		        return this.tickets;
		    }
		}
		
	}
}
