#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriCliModel;

namespace AriCliModel	
{
	public partial class PreviousMedicalRecord
	{
		private int previousMedicalRecordId;
		public virtual int PreviousMedicalRecordId
		{
			get
			{
				return this.previousMedicalRecordId;
			}
			set
			{
				this.previousMedicalRecordId = value;
			}
		}
		
		private string content;
		public virtual string Content
		{
			get
			{
				return this.content;
			}
			set
			{
				this.content = value;
			}
		}
		
		private Patient patient;
		public virtual Patient Patient
		{
			get
			{
				return this.patient;
			}
			set
			{
				this.patient = value;
			}
		}
		
	}
}
#pragma warning restore 1591
