#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public partial class Refractometry : ExaminationAssigned
	{
		private IList<WithoutGlassesTest> withoutGlassesTests = new List<WithoutGlassesTest>();
		public virtual IList<WithoutGlassesTest> WithoutGlassesTests 
		{ 
		    get
		    {
		        return this.withoutGlassesTests;
		    }
		}
		
		private IList<GlassesTest> glassesTests = new List<GlassesTest>();
		public virtual IList<GlassesTest> GlassesTests 
		{ 
		    get
		    {
		        return this.glassesTests;
		    }
		}
		
		private IList<ContactLensesTest> contactLensesTests = new List<ContactLensesTest>();
		public virtual IList<ContactLensesTest> ContactLensesTests 
		{ 
		    get
		    {
		        return this.contactLensesTests;
		    }
		}
		
		private IList<OpticalObjectiveExamination> opticalObjectiveExaminations = new List<OpticalObjectiveExamination>();
		public virtual IList<OpticalObjectiveExamination> OpticalObjectiveExaminations 
		{ 
		    get
		    {
		        return this.opticalObjectiveExaminations;
		    }
		}
		
		private IList<SubjectiveOpticalExamination> subjectiveOpticalExaminations = new List<SubjectiveOpticalExamination>();
		public virtual IList<SubjectiveOpticalExamination> SubjectiveOpticalExaminations 
		{ 
		    get
		    {
		        return this.subjectiveOpticalExaminations;
		    }
		}
		
		private IList<PrescriptionGlasses> prescriptionGlasses = new List<PrescriptionGlasses>();
		public virtual IList<PrescriptionGlasses> PrescriptionGlasses 
		{ 
		    get
		    {
		        return this.prescriptionGlasses;
		    }
		}
		
		private IList<Cycloplegia> cycloplegias = new List<Cycloplegia>();
		public virtual IList<Cycloplegia> Cycloplegias 
		{ 
		    get
		    {
		        return this.cycloplegias;
		    }
		}
		
	}
}
