#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriCliModel;


namespace AriCliModel	
{
	public partial class Replay
	{
		private int replayId;
		public virtual int ReplayId 
		{ 
		    get
		    {
		        return this.replayId;
		    }
		    set
		    {
		        this.replayId = value;
		    }
		}
		
		private DateTime replayDate;
		public virtual DateTime ReplayDate 
		{ 
		    get
		    {
		        return this.replayDate;
		    }
		    set
		    {
		        this.replayDate = value;
		    }
		}
		
		private string comments;
		public virtual string Comments 
		{ 
		    get
		    {
		        return this.comments;
		    }
		    set
		    {
		        this.comments = value;
		    }
		}
		
		private Channel channel;
		public virtual Channel Channel 
		{ 
		    get
		    {
		        return this.channel;
		    }
		    set
		    {
		        this.channel = value;
		    }
		}
		
		private User user;
		public virtual User User 
		{ 
		    get
		    {
		        return this.user;
		    }
		    set
		    {
		        this.user = value;
		    }
		}
		
		private Request request;
		public virtual Request Request 
		{ 
		    get
		    {
		        return this.request;
		    }
		    set
		    {
		        this.request = value;
		    }
		}
		
		private Service service;
		public virtual Service Service 
		{ 
		    get
		    {
		        return this.service;
		    }
		    set
		    {
		        this.service = value;
		    }
		}
		
	}
}
