#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace AriCliModel	
{
	public partial class WithoutGlassesTest : BasicOpticalTest
	{
		private int id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.id;
		    }
		    set
		    {
		        this.id = value;
		    }
		}
		
		private string comments;
		public virtual string Comments 
		{ 
		    get
		    {
		        return this.comments;
		    }
		    set
		    {
		        this.comments = value;
		    }
		}
		
		private decimal closeVisualAcuityRightEye;
		public virtual decimal CloseVisualAcuityRightEye 
		{ 
		    get
		    {
		        return this.closeVisualAcuityRightEye;
		    }
		    set
		    {
		        this.closeVisualAcuityRightEye = value;
		    }
		}
		
		private decimal closeVisualAcuityLeftEye;
		public virtual decimal CloseVisualAcuityLeftEye 
		{ 
		    get
		    {
		        return this.closeVisualAcuityLeftEye;
		    }
		    set
		    {
		        this.closeVisualAcuityLeftEye = value;
		    }
		}
		
		private decimal closeVisualAcuityBothEyes;
		public virtual decimal CloseVisualAcuityBothEyes 
		{ 
		    get
		    {
		        return this.closeVisualAcuityBothEyes;
		    }
		    set
		    {
		        this.closeVisualAcuityBothEyes = value;
		    }
		}
		
		private decimal farVisualAcuityRightEye;
		public virtual decimal FarVisualAcuityRightEye 
		{ 
		    get
		    {
		        return this.farVisualAcuityRightEye;
		    }
		    set
		    {
		        this.farVisualAcuityRightEye = value;
		    }
		}
		
		private decimal farVisualAcuityLeftEye;
		public virtual decimal FarVisualAcuityLeftEye 
		{ 
		    get
		    {
		        return this.farVisualAcuityLeftEye;
		    }
		    set
		    {
		        this.farVisualAcuityLeftEye = value;
		    }
		}
		
		private decimal farVisualAcuityBothEyes;
		public virtual decimal FarVisualAcuityBothEyes 
		{ 
		    get
		    {
		        return this.farVisualAcuityBothEyes;
		    }
		    set
		    {
		        this.farVisualAcuityBothEyes = value;
		    }
		}
		
		private Refractometry refractometry;
		public virtual Refractometry Refractometry 
		{ 
		    get
		    {
		        return this.refractometry;
		    }
		    set
		    {
		        this.refractometry = value;
		    }
		}
		
	}
}
