DELETE FROM invoice_line;
ALTER TABLE invoice_line AUTO_INCREMENT = 0;
DELETE FROM invoice;
ALTER TABLE invoice AUTO_INCREMENT = 0;
DELETE FROM appointment;
ALTER TABLE appointment AUTO_INCREMENT = 0;
DELETE FROM appointment_type;
ALTER TABLE appointment_type AUTO_INCREMENT = 0;
DELETE FROM diary;
ALTER TABLE diary AUTO_INCREMENT = 0;
DELETE FROM payment;
ALTER TABLE payment AUTO_INCREMENT = 0;
DELETE FROM ticket;
ALTER TABLE ticket AUTO_INCREMENT = 0;
DELETE FROM service_note;
ALTER TABLE service_note AUTO_INCREMENT = 0;
delete from insurance_service;
alter table insurance_service auto_increment = 0;
delete from insurance;
alter table insurance auto_increment = 0;
delete from service;
alter table service auto_increment = 0;
delete from service_category;
alter table service_category auto_increment = 0;
delete from tax_type;
alter table tax_type auto_increment = 0;
delete from tax_withholding_type;
alter table tax_withholding_type auto_increment = 0;
delete from address;
alter table address auto_increment = 0;
delete from email;
alter table email auto_increment = 0;
delete from telephone;
alter table telephone auto_increment = 0;
delete from policy;
alter table policy auto_increment = 0;
delete from payment_method;
alter table payment_method auto_increment = 0;
delete from professional;
alter table professional auto_increment = 0;
delete from clinic;
alter table clinic auto_increment = 0;
delete from customer;
alter table customer auto_increment = 0;
delete from patient;
alter table patient auto_increment = 0;
delete from person;
alter table person Auto_increment = 0;




