-- Script was generated by Devart dbForge Schema Compare for MySQL, Version 3.0.139.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/schemacompare
-- Script date 30/12/2013 13:26:20
-- Source server version: 5.6.10
-- Source connection string: User Id=root;Host=localhost;Database=ariclinic_miestetic;Character Set=utf8;
-- Target server version: 5.6.10
-- Target connection string: User Id=root;Host=localhost;Database=ariclinic_anes;Character Set=utf8;
-- Run this script against ariclinic_anes to synchronize it with ariclinic_miestetic
-- Please backup your target database before running this script

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';
USE ariclinic_anes;


--
-- Drop table "external_invoice_line"
--
DROP TABLE external_invoice_line;

--
-- Drop table "external_invoice"
--
DROP TABLE external_invoice;

--
-- Drop table "ticket2"
--
DROP TABLE ticket2;

--
-- Drop table "dolor_service_category"
--
DROP TABLE dolor_service_category;

--
-- Drop table "dolor_service"
--
DROP TABLE dolor_service;

--
-- Drop table "dolor_procedure"
--
DROP TABLE dolor_procedure;

--
-- Drop table "dolor_inurance_service"
--
DROP TABLE dolor_inurance_service;

--
-- Drop table "anesthetic_ticket2"
--
DROP TABLE anesthetic_ticket2;

--
-- Drop table "anesthetic_service_note2"
--
DROP TABLE anesthetic_service_note2;

--
-- Alter table "appointment_type"
--
ALTER TABLE appointment_type
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "base_visit_type"
--
ALTER TABLE base_visit_type
  CHANGE COLUMN nme nme VARCHAR(255) DEFAULT NULL FIRST,
  CHANGE COLUMN code code VARCHAR(255) NOT NULL AFTER nme,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "campaign"
--
ALTER TABLE campaign
  CHANGE COLUMN nme nme VARCHAR(255) DEFAULT NULL AFTER start_date,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "clinic"
--
ALTER TABLE clinic
  CHANGE COLUMN remote_ip remote_ip VARCHAR(30) DEFAULT NULL,
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "diagnostic"
--
ALTER TABLE diagnostic
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "diary"
--
ALTER TABLE diary
  CHANGE COLUMN nme nme VARCHAR(255) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "drug"
--
ALTER TABLE drug
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Create table "dup_patient"
--
CREATE TABLE dup_patient (
  person_id INT(11) NOT NULL,
  surname2 VARCHAR(30) DEFAULT NULL,
  surname1 VARCHAR(30) DEFAULT NULL,
  sex VARCHAR(1) DEFAULT NULL,
  open_date DATETIME DEFAULT NULL,
  oft_id INT(11) DEFAULT NULL,
  name VARCHAR(30) DEFAULT NULL,
  last_update DATETIME DEFAULT NULL,
  insurance_information VARCHAR(255) DEFAULT NULL,
  full_name VARCHAR(255) DEFAULT NULL,
  person_id2 INT(11) DEFAULT NULL,
  comments LONGTEXT DEFAULT NULL,
  clinic_id INT(11) DEFAULT NULL,
  born_date DATETIME DEFAULT NULL
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Alter table "examination_type"
--
ALTER TABLE examination_type
  CHANGE COLUMN nme nme VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN code code VARCHAR(255) NOT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "healthcare_company"
--
ALTER TABLE healthcare_company
  CHANGE COLUMN vatin vatin VARCHAR(20) DEFAULT NULL,
  CHANGE COLUMN name name VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN invoice_serial invoice_serial VARCHAR(30) DEFAULT NULL AFTER name,
  ADD COLUMN amendment_invoice_serial VARCHAR(255) NOT NULL AFTER hc_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "insurance"
--
ALTER TABLE insurance
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "nomenclator"
--
ALTER TABLE nomenclator
  CHANGE COLUMN name name VARCHAR(250) DEFAULT NULL FIRST,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "payment_method"
--
ALTER TABLE payment_method
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "process"
--
ALTER TABLE process
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL AFTER parent_process_id,
  CHANGE COLUMN description description LONGTEXT DEFAULT NULL AFTER name,
  CHANGE COLUMN code code VARCHAR(50) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "service_category"
--
ALTER TABLE service_category
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "source"
--
ALTER TABLE source
  CHANGE COLUMN nme nme VARCHAR(255) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "tax_type"
--
ALTER TABLE tax_type
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "tax_withholding_type"
--
ALTER TABLE tax_withholding_type
  CHANGE COLUMN name name VARCHAR(30) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "template"
--
ALTER TABLE template
  CHANGE COLUMN nme nme VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN content content TEXT DEFAULT NULL AFTER nme,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "unit_type"
--
ALTER TABLE unit_type
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "user_group"
--
ALTER TABLE user_group
  CHANGE COLUMN name name VARCHAR(50) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "visit_reason"
--
ALTER TABLE visit_reason
  CHANGE COLUMN nme nme VARCHAR(50) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "examination"
--
ALTER TABLE examination
  CHANGE COLUMN name name VARCHAR(255) DEFAULT NULL AFTER oft_id,
  CHANGE COLUMN code code VARCHAR(255) DEFAULT NULL AFTER name,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "lab_test"
--
ALTER TABLE lab_test
  CHANGE COLUMN nme nme VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN general_type general_type VARCHAR(10) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "permission"
--
ALTER TABLE permission
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "person"
--
ALTER TABLE person
  CHANGE COLUMN full_name full_name VARCHAR(100) DEFAULT NULL AFTER person_id,
  CHANGE COLUMN voa_class voa_class VARCHAR(255) DEFAULT NULL AFTER full_name,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "user"
--
ALTER TABLE user
  CHANGE COLUMN password password VARCHAR(30) NOT NULL AFTER profile,
  CHANGE COLUMN name name VARCHAR(50) NOT NULL AFTER password,
  CHANGE COLUMN login login VARCHAR(30) NOT NULL AFTER name,
  CHANGE COLUMN code code VARCHAR(255) DEFAULT NULL AFTER login,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "address"
--
ALTER TABLE address
  CHANGE COLUMN type type VARCHAR(10) DEFAULT NULL,
  CHANGE COLUMN street2 street2 VARCHAR(100) DEFAULT NULL,
  CHANGE COLUMN street street VARCHAR(50) DEFAULT NULL,
  CHANGE COLUMN province province VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN post_code post_code VARCHAR(10) DEFAULT NULL,
  CHANGE COLUMN country country VARCHAR(30) DEFAULT NULL AFTER hc_id,
  CHANGE COLUMN city city VARCHAR(30) DEFAULT NULL AFTER clinic_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

ALTER TABLE address
  ADD CONSTRAINT ref_address_person FOREIGN KEY (person_id)
    REFERENCES person(person_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table "customer"
--
ALTER TABLE customer
  CHANGE COLUMN vat_in vat_in VARCHAR(25) DEFAULT NULL AFTER person_id,
  CHANGE COLUMN comercial_name comercial_name VARCHAR(50) DEFAULT NULL AFTER oft_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "email"
--
ALTER TABLE email
  CHANGE COLUMN url url VARCHAR(50) DEFAULT NULL,
  CHANGE COLUMN type type VARCHAR(10) DEFAULT NULL AFTER url,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "log"
--
ALTER TABLE log
  CHANGE COLUMN remote_address remote_address VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN page page VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN action action VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "patient"
--
ALTER TABLE patient
  CHANGE COLUMN surname2 surname2 VARCHAR(30) DEFAULT NULL AFTER person_id,
  CHANGE COLUMN surname1 surname1 VARCHAR(30) DEFAULT NULL AFTER surname2,
  CHANGE COLUMN sex sex VARCHAR(1) DEFAULT NULL,
  CHANGE COLUMN name name VARCHAR(30) DEFAULT NULL AFTER oft_id,
  CHANGE COLUMN insurance_information insurance_information VARCHAR(255) DEFAULT NULL AFTER last_update,
  ADD COLUMN full_name VARCHAR(255) DEFAULT NULL AFTER insurance_information,
  CHANGE COLUMN comments comments LONGTEXT DEFAULT NULL AFTER person_id2,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "professional"
--
ALTER TABLE professional
  CHANGE COLUMN vatin vatin VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN type type VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN license license VARCHAR(255) DEFAULT NULL AFTER oft_id,
  CHANGE COLUMN invoice_serial invoice_serial VARCHAR(255) DEFAULT NULL AFTER license,
  CHANGE COLUMN comercial_name comercial_name VARCHAR(255) DEFAULT NULL AFTER commission,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "service"
--
ALTER TABLE service
  ADD COLUMN service_sub_category_id INT(11) DEFAULT NULL AFTER tax_type_id,
  CHANGE COLUMN name name VARCHAR(250) DEFAULT NULL AFTER oft_id,
  ROW_FORMAT = COMPACT,
  CHECKSUM = 0,
  DELAY_KEY_WRITE = 0,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

ALTER TABLE service
  ADD INDEX idx_service_service_sub_category_id (service_sub_category_id);

ALTER TABLE service
  ADD CONSTRAINT ref_service_service_sub_category FOREIGN KEY (service_sub_category_id)
    REFERENCES service_sub_category(service_sub_category_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table "telephone"
--
ALTER TABLE telephone
  CHANGE COLUMN type type VARCHAR(10) DEFAULT NULL FIRST,
  CHANGE COLUMN number number VARCHAR(20) DEFAULT NULL AFTER person_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "`procedure`"
--
ALTER TABLE `procedure`
  CHANGE COLUMN name name VARCHAR(250) DEFAULT NULL AFTER oft_id,
  ROW_FORMAT = COMPACT,
  CHECKSUM = 0,
  DELAY_KEY_WRITE = 0,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "appointment"
--
ALTER TABLE appointment
  DROP INDEX idx_appointment_father_appointment_appointment_id,
  CHANGE COLUMN subject subject VARCHAR(255) DEFAULT NULL AFTER user_id,
  CHANGE COLUMN status status VARCHAR(255) DEFAULT NULL AFTER subject,
  CHANGE COLUMN recurrence recurrence VARCHAR(255) DEFAULT NULL AFTER status,
  CHANGE COLUMN comments comments TEXT DEFAULT NULL AFTER diary_id,
  ADD COLUMN sms BIT(1) DEFAULT b'0' AFTER appointment_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

ALTER TABLE appointment
  ADD INDEX idx_appointment_info_father_appointment_appointment_id (father_appointment_appointment_id);

ALTER TABLE appointment
  DROP FOREIGN KEY ref_appointment_appointment_type;
ALTER TABLE appointment
  DROP INDEX idx_appointment_appointment_type_id;
ALTER TABLE appointment
  ADD CONSTRAINT ref_appointment_appointment_type FOREIGN KEY (appointment_type_id)
    REFERENCES appointment_type(appointment_type_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE appointment
  DROP FOREIGN KEY ref_appointment_diary;
ALTER TABLE appointment
  DROP INDEX idx_appointment_diary_id;
ALTER TABLE appointment
  ADD CONSTRAINT ref_appointment_diary FOREIGN KEY (diary_id)
    REFERENCES diary(diary_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE appointment
  DROP FOREIGN KEY ref_appointment_patient;
ALTER TABLE appointment
  DROP INDEX idx_appointment_person_id;
ALTER TABLE appointment
  ADD CONSTRAINT ref_appointment_patient FOREIGN KEY (person_id)
    REFERENCES patient(person_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE appointment
  DROP FOREIGN KEY ref_appointment_professional;
ALTER TABLE appointment
  DROP INDEX idx_appointment_person_id2;
ALTER TABLE appointment
  ADD CONSTRAINT ref_appointment_professional FOREIGN KEY (person_id2)
    REFERENCES professional(person_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE appointment
  DROP FOREIGN KEY ref_appointment_user;
ALTER TABLE appointment
  DROP INDEX idx_appointment_user_id;
ALTER TABLE appointment
  ADD CONSTRAINT ref_appointment_user FOREIGN KEY (user_id)
    REFERENCES user(user_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table "back_family"
--
ALTER TABLE back_family
  CHANGE COLUMN content content VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "back_ginecoloy"
--
ALTER TABLE back_ginecoloy
  CHANGE COLUMN menstrual_formula menstrual_formula VARCHAR(255) DEFAULT NULL AFTER person_id,
  CHANGE COLUMN menopause menopause VARCHAR(255) DEFAULT NULL AFTER menstrual_formula,
  CHANGE COLUMN menarche menarche VARCHAR(255) DEFAULT NULL AFTER menopause,
  CHANGE COLUMN content content LONGTEXT DEFAULT NULL AFTER date_of_last_mestrual,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "back_personal"
--
ALTER TABLE back_personal
  CHANGE COLUMN content content LONGTEXT DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "insurance_service"
--
ALTER TABLE insurance_service
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "invoice"
--
ALTER TABLE invoice
  CHANGE COLUMN serial serial VARCHAR(10) DEFAULT NULL AFTER total,
  CHANGE COLUMN invoice_key invoice_key VARCHAR(255) DEFAULT NULL AFTER invoice_number,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "parameter"
--
ALTER TABLE parameter
  ADD COLUMN sms_clave VARCHAR(255) DEFAULT NULL AFTER appointment_extension,
  ADD COLUMN sms_email VARCHAR(255) DEFAULT NULL AFTER sms_clave,
  ADD COLUMN sms_remitente VARCHAR(255) DEFAULT NULL AFTER sms_email,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "policy"
--
ALTER TABLE policy
  CHANGE COLUMN type type VARCHAR(20) DEFAULT NULL FIRST,
  CHANGE COLUMN policy_number policy_number VARCHAR(255) DEFAULT NULL AFTER type,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "previous_medical_record"
--
ALTER TABLE previous_medical_record
  CHANGE COLUMN content content LONGTEXT DEFAULT NULL AFTER person_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "professional_invoice"
--
ALTER TABLE professional_invoice
  CHANGE COLUMN serial serial VARCHAR(30) NOT NULL AFTER tax_whith_holding_percentage,
  CHANGE COLUMN invoice_key invoice_key VARCHAR(255) DEFAULT NULL AFTER invoice_number,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "anesthetic_service_note"
--
ALTER TABLE anesthetic_service_note
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

ALTER TABLE anesthetic_service_note
  ADD CONSTRAINT ref_anesthetic_service_note_invoice FOREIGN KEY (invoice_id)
    REFERENCES invoice(invoice_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE anesthetic_service_note
  ADD CONSTRAINT ref_anesthetic_service_note_professional_invoice FOREIGN KEY (invoice_id)
    REFERENCES professional_invoice(invoice_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table "base_visit"
--
ALTER TABLE base_visit
  CHANGE COLUMN vtype vtype VARCHAR(255) DEFAULT NULL FIRST,
  CHANGE COLUMN comments comments TEXT DEFAULT NULL AFTER oft_ref_visita,
  CHANGE COLUMN code code VARCHAR(255) DEFAULT NULL AFTER comments,
  CHANGE COLUMN voa_class voa_class VARCHAR(255) DEFAULT NULL AFTER appointment_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "service_note"
--
ALTER TABLE service_note
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "anesthetic_service_note_procedures"
--
ALTER TABLE anesthetic_service_note_procedures
  CHANGE COLUMN anesthetic_service_note_id anesthetic_service_note_id INT(11) NOT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "diagnostic_assigned"
--
ALTER TABLE diagnostic_assigned
  CHANGE COLUMN comments comments LONGTEXT DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "examination_assigned"
--
ALTER TABLE examination_assigned
  CHANGE COLUMN comments comments TEXT DEFAULT NULL,
  CHANGE COLUMN voa_class voa_class VARCHAR(255) DEFAULT NULL AFTER visit_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "general_payment"
--
ALTER TABLE general_payment
  CHANGE COLUMN description description VARCHAR(255) DEFAULT NULL AFTER general_payment_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "lab_test_assigned"
--
ALTER TABLE lab_test_assigned
  CHANGE COLUMN string_value string_value VARCHAR(255) DEFAULT NULL FIRST,
  CHANGE COLUMN comments comments TEXT DEFAULT NULL AFTER lab_test_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "ophthalmologic_visit"
--
ALTER TABLE ophthalmologic_visit
  CHANGE COLUMN diagnostic_details diagnostic_details VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "procedure_assigned"
--
ALTER TABLE procedure_assigned
  CHANGE COLUMN comments comments TEXT DEFAULT NULL AFTER person_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "treatment"
--
ALTER TABLE treatment
  CHANGE COLUMN recommend recommend VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN person_id2 person_id2 INT(11) NOT NULL AFTER quantity,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "anesthetic_ticket"
--
ALTER TABLE anesthetic_ticket
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "ant_segment"
--
ALTER TABLE ant_segment
  CHANGE COLUMN tyndall tyndall VARCHAR(255) DEFAULT NULL FIRST,
  CHANGE COLUMN pupil pupil VARCHAR(255) DEFAULT NULL AFTER tyndall,
  CHANGE COLUMN iris iris VARCHAR(255) DEFAULT NULL AFTER visit_id,
  CHANGE COLUMN eyebrows_comments eyebrows_comments VARCHAR(255) DEFAULT NULL AFTER eyestrain_l_e,
  CHANGE COLUMN crystalline crystalline VARCHAR(255) DEFAULT NULL AFTER eyebrows_comments,
  CHANGE COLUMN cornea cornea VARCHAR(255) DEFAULT NULL AFTER crystalline,
  CHANGE COLUMN conjunctiva conjunctiva VARCHAR(255) DEFAULT NULL AFTER cornea,
  CHANGE COLUMN chamber chamber VARCHAR(255) DEFAULT NULL AFTER conjunctiva,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "biometry"
--
ALTER TABLE biometry
  CHANGE COLUMN formula formula VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "fundus"
--
ALTER TABLE fundus
  CHANGE COLUMN vitreous vitreous TEXT DEFAULT NULL FIRST,
  CHANGE COLUMN vessels vessels TEXT DEFAULT NULL AFTER vitreous,
  CHANGE COLUMN periphery periphery TEXT DEFAULT NULL AFTER vessels,
  CHANGE COLUMN optic_nerve optic_nerve TEXT DEFAULT NULL,
  CHANGE COLUMN macula macula TEXT DEFAULT NULL AFTER visit_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "invoice_line"
--
ALTER TABLE invoice_line
  CHANGE COLUMN description description VARCHAR(255) DEFAULT NULL AFTER invoice_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "mot_append"
--
ALTER TABLE mot_append
  CHANGE COLUMN periocular_area periocular_area TEXT DEFAULT NULL FIRST,
  CHANGE COLUMN eye_motility eye_motility TEXT DEFAULT NULL AFTER id,
  CHANGE COLUMN eyebrows eyebrows TEXT DEFAULT NULL AFTER eye_motility,
  CHANGE COLUMN comments comments TEXT DEFAULT NULL AFTER eyebrows,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "paquimetry"
--
ALTER TABLE paquimetry
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "payment"
--
ALTER TABLE payment
  CHANGE COLUMN description description VARCHAR(50) DEFAULT NULL AFTER general_payment_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "professional_invoice_line"
--
ALTER TABLE professional_invoice_line
  CHANGE COLUMN description description VARCHAR(255) DEFAULT NULL AFTER invoice_line_id,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "refractometry"
--
ALTER TABLE refractometry
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "topography"
--
ALTER TABLE topography
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "contact_lenses_test"
--
ALTER TABLE contact_lenses_test
  CHANGE COLUMN far_visual_acuity_right_eye far_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_left_eye far_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_both_eyes far_visual_acuity_both_eyes VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN comments comments VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_visual_acuity_right_eye close_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_visual_acuity_left_eye close_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_visual_acuity_both_eyes close_visual_acuity_both_eyes VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "cycloplegia"
--
ALTER TABLE cycloplegia
  CHANGE COLUMN far_visual_acuity_right_eye far_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_left_eye far_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_right_eye far_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_left_eye far_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prism_left_eye far_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prims_right_eye far_prims_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_right_eye far_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_left_eye far_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_centers far_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_right_eye far_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_left_eye far_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_acuity far_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN comments comments VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_right_eye close_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_left_eye close_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_right_eye close_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_left_eye close_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_right_eye close_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_left_eye close_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_centers close_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_right_eye close_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_left_eye close_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_right_eye close_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_left_eye close_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity close_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_right_eye both_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_left_eye both_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_right_eye both_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_left_eye both_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_right_eye both_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_left_eye both_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_centers both_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_right_eye both_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_left_eye both_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_right_eye both_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_left_eye both_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity both_acuity VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "glasses_test"
--
ALTER TABLE glasses_test
  CHANGE COLUMN far_visual_acuity_right_eye far_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_left_eye far_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_right_eye far_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_left_eye far_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prism_left_eye far_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prims_right_eye far_prims_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_right_eye far_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_left_eye far_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_centers far_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_right_eye far_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_left_eye far_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_acuity far_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN comments comments VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_right_eye close_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_left_eye close_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_right_eye close_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_left_eye close_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_right_eye close_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_left_eye close_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_centers close_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_right_eye close_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_left_eye close_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_right_eye close_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_left_eye close_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity close_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_right_eye both_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_left_eye both_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_right_eye both_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_left_eye both_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_right_eye both_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_left_eye both_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_centers both_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_right_eye both_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_left_eye both_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_right_eye both_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_left_eye both_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity both_acuity VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "optical_objective_examination"
--
ALTER TABLE optical_objective_examination
  CHANGE COLUMN k2_right_eye k2_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN k2_left_eye k2_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN k1_right_eye k1_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN k1_left_eye k1_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_right_eye far_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_left_eye far_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_right_eye far_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_left_eye far_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prism_left_eye far_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prims_right_eye far_prims_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_right_eye far_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_left_eye far_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_centers far_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_right_eye far_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_left_eye far_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_acuity far_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN comments comments VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_right_eye close_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_left_eye close_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_right_eye close_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_left_eye close_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_right_eye close_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_left_eye close_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_centers close_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_right_eye close_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_left_eye close_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_right_eye close_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_left_eye close_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity close_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_right_eye both_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_left_eye both_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_right_eye both_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_left_eye both_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_right_eye both_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_left_eye both_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_centers both_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_right_eye both_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_left_eye both_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_right_eye both_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_left_eye both_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity both_acuity VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "prescription_glasses"
--
ALTER TABLE prescription_glasses
  CHANGE COLUMN sign_MD sign_MD VARCHAR(255) NOT NULL FIRST,
  CHANGE COLUMN far_visual_acuity_right_eye far_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL AFTER id,
  CHANGE COLUMN far_visual_acuity_left_eye far_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL AFTER far_visual_acuity_right_eye,
  CHANGE COLUMN far_sphericity_right_eye far_sphericity_right_eye VARCHAR(255) DEFAULT NULL AFTER far_visual_acuity_left_eye,
  CHANGE COLUMN far_sphericity_left_eye far_sphericity_left_eye VARCHAR(255) DEFAULT NULL AFTER far_sphericity_right_eye,
  CHANGE COLUMN far_prism_left_eye far_prism_left_eye VARCHAR(255) DEFAULT NULL AFTER far_sphericity_left_eye,
  CHANGE COLUMN far_prims_right_eye far_prims_right_eye VARCHAR(255) DEFAULT NULL AFTER far_prism_left_eye,
  CHANGE COLUMN far_cylinder_right_eye far_cylinder_right_eye VARCHAR(255) DEFAULT NULL AFTER far_prims_right_eye,
  CHANGE COLUMN far_cylinder_left_eye far_cylinder_left_eye VARCHAR(255) DEFAULT NULL AFTER far_cylinder_right_eye,
  CHANGE COLUMN far_centers far_centers VARCHAR(255) DEFAULT NULL AFTER far_cylinder_left_eye,
  CHANGE COLUMN far_axis_right_eye far_axis_right_eye VARCHAR(255) DEFAULT NULL AFTER far_centers,
  CHANGE COLUMN far_axis_left_eye far_axis_left_eye VARCHAR(255) DEFAULT NULL AFTER far_axis_right_eye,
  CHANGE COLUMN far_acuity far_acuity VARCHAR(255) DEFAULT NULL AFTER far_axis_left_eye,
  CHANGE COLUMN comments comments VARCHAR(255) DEFAULT NULL AFTER far_acuity,
  CHANGE COLUMN close_sphericity_right_eye close_sphericity_right_eye VARCHAR(255) DEFAULT NULL AFTER comments,
  CHANGE COLUMN close_sphericity_left_eye close_sphericity_left_eye VARCHAR(255) DEFAULT NULL AFTER close_sphericity_right_eye,
  CHANGE COLUMN close_prism_right_eye close_prism_right_eye VARCHAR(255) DEFAULT NULL AFTER close_sphericity_centers,
  CHANGE COLUMN close_prism_left_eye close_prism_left_eye VARCHAR(255) DEFAULT NULL AFTER close_prism_right_eye,
  CHANGE COLUMN close_cylinder_right_eye close_cylinder_right_eye VARCHAR(255) DEFAULT NULL AFTER close_prism_left_eye,
  CHANGE COLUMN close_cylinder_left_eye close_cylinder_left_eye VARCHAR(255) DEFAULT NULL AFTER close_cylinder_right_eye,
  CHANGE COLUMN close_centers close_centers VARCHAR(255) DEFAULT NULL AFTER close_cylinder_left_eye,
  CHANGE COLUMN close_axis_right_eye close_axis_right_eye VARCHAR(255) DEFAULT NULL AFTER close_centers,
  CHANGE COLUMN close_axis_left_eye close_axis_left_eye VARCHAR(255) DEFAULT NULL AFTER close_axis_right_eye,
  CHANGE COLUMN close_acuity_right_eye close_acuity_right_eye VARCHAR(255) DEFAULT NULL AFTER close_axis_left_eye,
  CHANGE COLUMN close_acuity_left_eye close_acuity_left_eye VARCHAR(255) DEFAULT NULL AFTER close_acuity_right_eye,
  CHANGE COLUMN close_acuity close_acuity VARCHAR(255) DEFAULT NULL AFTER close_acuity_left_eye,
  CHANGE COLUMN both_sphericity_right_eye both_sphericity_right_eye VARCHAR(255) DEFAULT NULL AFTER close_acuity,
  CHANGE COLUMN both_sphericity_left_eye both_sphericity_left_eye VARCHAR(255) DEFAULT NULL AFTER both_sphericity_right_eye,
  CHANGE COLUMN both_prism_right_eye both_prism_right_eye VARCHAR(255) DEFAULT NULL AFTER both_sphericity_left_eye,
  CHANGE COLUMN both_prism_left_eye both_prism_left_eye VARCHAR(255) DEFAULT NULL AFTER both_prism_right_eye,
  CHANGE COLUMN both_cylinder_right_eye both_cylinder_right_eye VARCHAR(255) DEFAULT NULL AFTER both_prism_left_eye,
  CHANGE COLUMN both_cylinder_left_eye both_cylinder_left_eye VARCHAR(255) DEFAULT NULL AFTER both_cylinder_right_eye,
  CHANGE COLUMN both_centers both_centers VARCHAR(255) DEFAULT NULL AFTER both_cylinder_left_eye,
  CHANGE COLUMN both_axis_right_eye both_axis_right_eye VARCHAR(255) DEFAULT NULL AFTER both_centers,
  CHANGE COLUMN both_axis_left_eye both_axis_left_eye VARCHAR(255) DEFAULT NULL AFTER both_axis_right_eye,
  CHANGE COLUMN both_acuity_right_eye both_acuity_right_eye VARCHAR(255) DEFAULT NULL AFTER both_axis_left_eye,
  CHANGE COLUMN both_acuity_left_eye both_acuity_left_eye VARCHAR(255) DEFAULT NULL AFTER both_acuity_right_eye,
  CHANGE COLUMN both_acuity both_acuity VARCHAR(255) DEFAULT NULL AFTER both_acuity_left_eye,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "subjective_optical_examination"
--
ALTER TABLE subjective_optical_examination
  CHANGE COLUMN far_visual_acuity_right_eye far_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_left_eye far_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_right_eye far_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_sphericity_left_eye far_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prism_left_eye far_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_prims_right_eye far_prims_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_right_eye far_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_cylinder_left_eye far_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_centers far_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_right_eye far_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_axis_left_eye far_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_acuity far_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN comments comments VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_right_eye close_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_sphericity_left_eye close_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_right_eye close_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_prism_left_eye close_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_right_eye close_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_cylinder_left_eye close_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_centers close_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_right_eye close_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_axis_left_eye close_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_right_eye close_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity_left_eye close_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_acuity close_acuity VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_right_eye both_sphericity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_sphericity_left_eye both_sphericity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_right_eye both_prism_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_prism_left_eye both_prism_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_right_eye both_cylinder_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_cylinder_left_eye both_cylinder_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_centers both_centers VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_right_eye both_axis_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_axis_left_eye both_axis_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_right_eye both_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity_left_eye both_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN both_acuity both_acuity VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "without_glasses_test"
--
ALTER TABLE without_glasses_test
  CHANGE COLUMN far_visual_acuity_right_eye far_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_left_eye far_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN far_visual_acuity_both_eyes far_visual_acuity_both_eyes VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN comments comments VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_visual_acuity_right_eye close_visual_acuity_right_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_visual_acuity_left_eye close_visual_acuity_left_eye VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN close_visual_acuity_both_eyes close_visual_acuity_both_eyes VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Create view "vw_solicitudes_general"
--
CREATE 
VIEW vw_solicitudes_general
AS (SELECT
    `r`.`request_date_time` AS `FECHA`,
    YEAR(`r`.`request_date_time`) AS `ANO`,
    MONTH(`r`.`request_date_time`) AS `MES`,
    DAYOFMONTH(`r`.`request_date_time`) AS `DIA`,
    WEEK(`r`.`request_date_time`, 0) AS `SEMANA`,
    WEEKDAY(`r`.`request_date_time`) AS `DIASEMANA`,
    `r`.`status` AS `ESTADO`,
    `u`.`name` AS `USUARIO_SOLICITUD`,
    `r`.`full_name` AS `CANDIDATO`,
    `p`.`full_name` AS `PACIENTE`,
    `c`.`comercial_name` AS `CLIENTE`,
    `c`.`vat_in` AS `CIF`,
    IF((`r`.`sex` = _utf8 'W'), _utf8 'MUJER', _utf8 'HOMBRE') AS `SEXO_CANDIDATO`,
    IF((`p`.`sex` = _utf8 'W'), _utf8 'MUJER', _utf8 'HOMBRE') AS `SEXO_PACIENTE`,
    `s`.`name` AS `SERVICIO`,
    `ap`.`post_code` AS `CP_PACIENTE`,
    `ac`.`post_code` AS `CP_CLIENTE`,
    IF(ISNULL(`ap`.`post_code`), `ac`.`post_code`, `ap`.`post_code`) AS `CPOSTAL`,
    `r`.`email` AS `EMAIL_CANDIDATO`,
    `ep`.`url` AS `EMAIL_PACIENTE`,
    `ec`.`url` AS `EMAIL_CLIENTE`,
    IF(ISNULL(`r`.`email`), `ep`.`url`, `r`.`email`) AS `EMAIL`,
    `cpg`.`nme` AS `CAMPANYA`,
    `src`.`nme` AS `FUENTE`,
    `r`.`comments` AS `COMENTARIO`,
    `rpl`.`replay_date` AS `FECHA_RESPUESTA`,
    (TIME_TO_SEC(TIMEDIFF(`r`.`request_date_time`, `rpl`.`replay_date`)) / 3600) AS `RETRASO_RESPUESTA`,
    `rpls`.`name` AS `SERVICIO_RESPUESTA`,
    `rpl`.`comments` AS `RESPUESTA`,
    `est`.`ttal` AS `TOTAL_PRESUPUESTO`,
    `est`.`estimate_date` AS `FECHA_PRESUPUESTO`,
    (TIME_TO_SEC(TIMEDIFF(`r`.`request_date_time`, `est`.`estimate_date`)) / 3600) AS `RETRASO_PRESUPUESTO`,
    `s2`.`name` AS `SERVICIO_PRESUPUESTADO`,
    `ins`.`price` AS `PRECIO_ACTUAL`,
    `estl`.`amount` AS `PRECIO_PRESUPUESTO`,
    `estl`.`discount` AS `DESCUENTO_PRESUPUESTO`,
    `est`.`comments` AS `DESCRIPCION_PRESUPUESTO`,
    (`estl`.`amount` - `estl`.`discount`) AS `IMPORTE_PRESUPUESTO`
  FROM ((((((((((((((((`request` `r`
    LEFT JOIN `replay` `rpl`
      ON ((`rpl`.`request_id` = `r`.`request_id`)))
    LEFT JOIN `service` `rpls`
      ON ((`rpls`.`service_id` = `rpl`.`service_id`)))
    LEFT JOIN `estimate` `est`
      ON ((`est`.`request_id` = `r`.`request_id`)))
    LEFT JOIN `estimate_line` `estl`
      ON ((`estl`.`estimate_id` = `est`.`estimate_id`)))
    LEFT JOIN `insurance_service` `ins`
      ON ((`ins`.`insurance_service_id` = `estl`.`insurance_service_id`)))
    LEFT JOIN `service` `s2`
      ON ((`s2`.`service_id` = `ins`.`service_id`)))
    LEFT JOIN `user` `u`
      ON ((`u`.`user_id` = `r`.`user_id`)))
    LEFT JOIN `patient` `p`
      ON ((`p`.`person_id` = `r`.`person_id`)))
    LEFT JOIN `customer` `c`
      ON ((`c`.`person_id` = `p`.`person_id2`)))
    LEFT JOIN `service` `s`
      ON ((`s`.`service_id` = `r`.`service_id`)))
    LEFT JOIN `address` `ap`
      ON (((`ap`.`person_id` = `p`.`person_id`) AND (`ap`.`type` = _utf8 'Primary'))))
    LEFT JOIN `address` `ac`
      ON (((`ac`.`person_id` = `c`.`person_id`) AND (`ac`.`type` = _utf8 'Primary'))))
    LEFT JOIN `email` `ep`
      ON (((`ep`.`person_id` = `p`.`person_id`) AND (`ep`.`type` = _utf8 'Primary'))))
    LEFT JOIN `email` `ec`
      ON (((`ec`.`person_id` = `c`.`person_id`) AND (`ec`.`type` = _utf8 'Primary'))))
    LEFT JOIN `campaign` `cpg`
      ON ((`cpg`.`campaign_id` = `r`.`campaign_id`)))
    LEFT JOIN `source` `src`
      ON ((`src`.`source_id` = `r`.`source_id`))));

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
